### ISSUE TITLE
[Favorite Resources] Wrong icon for Sage Hatch

### ISSUE THREAD

**Issue by Tyolan** [O-n-y/oxy.mods#1]
The icon for "Sage Hatch" is not the good one ("Normal Hatch" used instead).

**Comment by O-n-y** [comment]
Hi, all sprites are taken from game "ui" animation part, this mean there is wrong sprite there for this particular species fo hatch, this need to be fixed by Klei unfortunatly.

```

//KBatchedAnimController component
Def.GetUISpriteFromMultiObjectAnim(component.AnimFiles[0], "ui",  false, string.Empty);
```

**Comment by Tyolan** [comment]
Oh ok. I forgot to say it was for the "Sage Hatch" **Egg** (because we can't see critters with your mod yet).
This bug is weird because in the database we can clearly see that the icon for the Sage Hatch egg is the good one. I presume you use an other one for the icons.

**Comment by Tyolan** [comment]
Same for the egg cracker. The icon is fine ingame for the Sage Hatch Egg.

**Comment by O-n-y** [comment]
I created  a ticked for hatch egg, but to be honest i am not sure they will fix it
https://forums.kleientertainment.com/klei-bug-tracker/oni/egg-of-sage-hatch-sprite-if-wrong-for-ui-part-of-kbatchedanimcontrolleranimfiles0-r22304/

**Comment by O-n-y** [comment]
> Same for the egg cracker. The icon is fine ingame for the Sage Hatch Egg.
maybe later i will check what other source i can use

**Comment by Tyolan** [comment]
Thank you very much for that and for your work !
Hope to see the critter inventory compatibility soon. Have a nice day.

**Comment by O-n-y** [comment]
fixed

**Comment by Tyolan** [comment]
Yes ! Great, it works perfectly. Thx again.
