### ISSUE TITLE
feature request: alphanumeric listing/ordering mods by column

### ISSUE THREAD

**Issue by yeliabmit** [O-n-y/oxy.mods#102]
It would be super useful if it was possible to reorder mods not just to determine their loading order but also to see them in order of their last update, version number, etc.  Filtering mods by author sort of allows you to see mods where the author is actively keeping them up to date and squashing bugs, but it's not really the same.  Thank you!

**Comment by O-n-y** [comment]
this could cause problems, because mods order determine which mod will load first, and some mods could cause problems if loaded 'out of order', so it is technical, not visual element with current game implementation of the mods
