### ISSUE TITLE
Mod Failure ONI Spaced Out after Game Update 535720 - Hot Shots

### ISSUE THREAD

**Issue by steven4u2nv** [O-n-y/oxy.mods#107]
Mod Failure ONI Spaced Out after Game Update 535720 - Hot Shots.  My computer is a MAC and up to date.  After installing the listed game update your mod is failing to load.  

I really love the mod for casual play.

Thanks again for your hard work.

Steve

**Comment by O-n-y** [comment]
If you report something and want to get help, at least try to do this as it sayd in section `How to Report Bugs` https://github.com/O-n-y/oxy.mods

_(you haven't even posted the mod **name** you are talking about)_

If you are talking about DGSM (most likely): https://github.com/O-n-y/oxy.mods/issues/104

**Comment by O-n-y** [comment]
as no additional  information was provided, i am closing this one
