### ISSUE TITLE
DGSM UI 

### ISSUE THREAD

**Issue by Meister000** [O-n-y/oxy.mods#109]
i rolled oni back so i can play but when i tryed to change config it get cut of and i have to close the game 

![Unbenannt](https://user-images.githubusercontent.com/98042958/209436687-d3daa638-cb55-4c62-952b-ca4a8338c190.PNG)

**Comment by O-n-y** [comment]
please post your settings for
1. monitor resolution
2. windows scale
3. in-game scale
4. any other custom graphics related settings

**Comment by Meister000** [comment]
1366x768 60hz  defaulte and no

**Comment by Meister000** [comment]
the in game ui scale has no impacte

**Comment by O-n-y** [comment]
`in-game scale`  - please, do answer if you have it custom value, or default.

**Comment by Meister000** [comment]
its on 100

**Comment by O-n-y** [comment]
will be fixed in upcoming release build

**Comment by O-n-y** [comment]
fixed in 3.4.40.68 release build
