### ISSUE TITLE
Production quantity cannot be set with Favorite Buildings

### ISSUE THREAD

**Issue by Calio-Templar** [O-n-y/oxy.mods#11]
With favorite buildings oob setting, quantity number setting on production by numbers will be interrupted to custiom key bindings

**Comment by O-n-y** [comment]
1) please follow information how to report bug and provide all data (https://github.com/O-n-y/oxy.mods)
2) not sure what exactly mean, provide more details and maybe screenshot.

**Comment by O-n-y** [comment]
closing issue as no more details were provided
