### ISSUE TITLE
[DGSM] [Feature Request] drop-down tabs support

### ISSUE THREAD

**Issue by taozhiyu** [O-n-y/oxy.mods#112]
Is it possible to use drop-down tabs (or even group drop-down tabs) 

instead of the button "Change" for selecting properties, attributes, etc.

![image](https://user-images.githubusercontent.com/49258735/214046860-62f09d8b-183a-4e95-a0c9-93dec70a67f0.png)

As you can see in the box on the right in the screenshot above, there aren't really many attributes, but there are quite a few positive traits

**Comment by taozhiyu** [comment]
It looks like this should be the `PlanScreen` class, but unfortunately I have no experience in c# development

**Comment by O-n-y** [comment]
I hope to push changes to UI interactions in near future :) (started the work on those)

**Comment by O-n-y** [comment]
UI improvements preview are on Discord 😉

**Comment by O-n-y** [comment]
changed made in last release build
