### ISSUE TITLE
Debug console mod does not open

### ISSUE THREAD

**Issue by onifanatic** [O-n-y/oxy.mods#113]
When attempting to use the debug console mod (https://steamcommunity.com/sharedfiles/filedetails/?id=2041219184&searchtext=debug+console) for the first time I was unable to get it to work. The documentation states "Creates console window with debug information" but no console window was created. Please let me know if there's any additional info or debug flags I can configure to help diagnose.

**Comment by O-n-y** [comment]
Please provide information: https://github.com/O-n-y/oxy.mods#how-to-report-bugs

**Comment by O-n-y** [comment]
As no information provided, i am closing this one
