### ISSUE TITLE
[No Drop] ArgumentOutOfRangeException: Index was out of range

### ISSUE THREAD

**Issue by jpetays** [O-n-y/oxy.mods#119]
Mod version: 1.3.0.4
Game version: U46-552078-S

DLC enabled, classic Ocean asteroid cycle 33.

I did not do anything special in the game, the game just crashed with this error message.
It might be possible that a new cycle was started when the error happened, but I did not pay any attention to this.
I do not play very often and this is the first time I got this error.
It might be related to latest updates, but most probably not.

This is single threaded application so the problem should be found inside Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent FixedUpdate method?
If the the offending index was not calculated inside this method, then things like this can happen, right?

Error message from clipboard:
```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.RemoveAt (System.Int32 index) (at <b69d74babc594991a6033f935c4f5292>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () (at <b69d74babc594991a6033f935c4f5292>:0)

Build: U46-552078-S
```

**Comment by O-n-y** [comment]
please do the following:
1) disable all other mods (you can leave any of mine one)
2) install, enable mod manager
3) screenshot mods list where no drop mod is visible in mod manager, so i can see the version
4) try to replicate this issue with this settings
5) send me send file, where i can replicate this issue

**Comment by O-n-y** [comment]
as no more info was provided, i am closing this one
