### ISSUE TITLE
Mod manager crash when reopening the mod page

### ISSUE THREAD

**Issue by Xiaro** [O-n-y/oxy.mods#12]
So I open the mod page and I click on "Enable All". Then I restart the game. When the game is back up, I go the mod page. But the mod list is in a wrong format. When I try to open the mod page again, it crashes.

The funny thing is, this only happens after enabling all mod. It doesn't happen if I only enable a single mod.

Here is the output log from the game. 
[output_log.txt](https://github.com/O-n-y/oxy.mods/files/4314512/output_log.txt)

I also record a video of how this happened.
https://drive.google.com/file/d/1qIHoSp9s3vkbkObDDQYFE-BFufqn89y0

**Comment by O-n-y** [comment]
Disable other mods you have, some of them broke Mod Manager. 
This is not a mod issue.

**Comment by O-n-y** [comment]
Closing as no more information was provided by author
