### ISSUE TITLE
[DGSM + No Drop]Crashes on startup, not compatible with spaced out!

### ISSUE THREAD

**Issue by xhilusius** [O-n-y/oxy.mods#120]
Suddenly can no longer play with mods, mod manager indicates they are not compatible with Spaced Out!
![image](https://user-images.githubusercontent.com/23653382/233793238-e32198e5-7a16-4b66-a713-ffb050c8997e.png)

**Comment by O-n-y** [comment]
Please do repect how to report issue properly.

Last version of No Drop and DGSM are fully compatible with the recent game patch, the most common issue could be you have some other mod broke the mods.

If you have issue, do follow steps for _**Throubleshooting**_: https://github.com/O-n-y/oxy.mods
and if the issue after those are still there, report it as it is said in **How to Report Bugs**
