### ISSUE TITLE
[DGSM] 3.4.40.104 Non-starting dupes not available for printing (Meep, Liam, etc) from the Printing Pod

### ISSUE THREAD

**Issue by Jemsterr** [O-n-y/oxy.mods#122]
Meep and Liam (and the other dupes that are only available after the start of the game) are not available to be printed from the printing pod with DGSM enabled.

**Comment by Jemsterr** [comment]
(Not tested with the enable all dupes at start selected, since I didn't want to enable them at the start)

**Comment by O-n-y** [comment]
Please do follow steps how to report issue:
https://github.com/O-n-y/oxy.mods


Also for advanced Duplicants to be available in game within any time (they distributed by how long particular game played and also rarity), you need to check setting in DGSM "Unlock all Duplicants"

Be aware that having concrete Duple - is only a chance, so if you want some particular appearance - you need to roll for it,

I have planned to make appearance also choosable, but it is not yet implemented, due to lack of free time

**Comment by Jemsterr** [comment]
OS: Linux  (Kernel 6.3.1-arch2-1)
Build: U46-552078-VD (Base game, DLC not enabled)

The "Unlock All Duplicants" setting claims to only affect "Starting crew choice" but I will test with it enabled.

For clarity, this world is now 268 cycles old, with many many rerolls, and have not been offered a Meep nor a Liam. (I haven't looked for other dupes specifically)  After seeing a comment in the workshop confirming that someone else had this issue, I decided to open an Issue.

Testing now with "Unlock All Duplicants personalities for Starting crew choice" enabled.

**Comment by Jemsterr** [comment]
Confirmed.  The "Unlock All Duplicants personalities for Starting crew choice" affects the printing pod as well as the Starting crew choice.  Within 10 rerolls, I was offered both a Meep and a Liam. (I already have 16 dupes, so the pool being offered is smaller)

**Comment by O-n-y** [comment]
"So, it seems that the option disables those dupes from the printing pod in addition to adding them to the Starting crew choice."

The option should not disabling anything (i.e. if not enabled it won't do anything) - it just make the game to generate all Duplicants by itself, but with it enabled - it garantee you will have those even if game think you should not have. 

But i will check if there is some sort of a problem there

**Comment by Jemsterr** [comment]
Sorry if the wording sounded aggressive, I was trying to accurately describe the behaviour I was seeing.  I am just testing for another 3 cycles on a new world to see if any of the below listed duplicants are available via reroll.

According to the wiki (Unless an ONI update broke it rather than your mod?) "Ari, Mae, Ada, Meep, Liam, and Banhi can only be spawned from the Printing Pod after the start."

**Comment by O-n-y** [comment]
i will check it out, thanks!

**Comment by O-n-y** [comment]
Please do provide save file where this can be replicated

**Comment by Jemsterr** [comment]
[The Beautiful Rat's Nest.zip](https://github.com/O-n-y/oxy.mods/files/11538869/The.Beautiful.Rat.s.Nest.zip)

Save file with only DGSM (Mod settings attached) 
![image](https://github.com/O-n-y/oxy.mods/assets/17609227/10a408ed-1ad8-44de-a548-ef14fffa2123)
 and Mod Updater. New world. Cycle 3. First pod activation.  No matter how many times I hit Reroll or reload the save, I do not get offered Ari, Mae, Ada, Meep, Liam, or Banhi.
 
 After removing all mods, it only took 3 reloads to get an Ada offered:
![image](https://github.com/O-n-y/oxy.mods/assets/17609227/137434ff-4bd3-4a76-9add-944bc4c7c48a)

**Comment by O-n-y** [comment]
fixed on next release build 
DGSM 3.4.41.135+
