### ISSUE TITLE
[WGMS] Crash at opening.

### ISSUE THREAD

**Issue by bta908** [O-n-y/oxy.mods#124]
I have mod manager 2.13.7.125 and WGSM. WGSM is showing its up to date but is crashing my game. I have gone throw clearning all the caush on my game.  I also did a frash install of this game and its still crashing.  

with the mod manager it is showing that the mod WGSM is up to date yet it still crashes my game.

would love to use this mod as it's help me make a few good worlds in the past.

**Comment by O-n-y** [comment]
Will be fixed in upcoming release version (currently in testing via patrons)
2.3.2.31  +

**Comment by O-n-y** [comment]
fixed with released build
