### ISSUE TITLE
WGSM - ignoring enable/disable state of geodes/underground ocean/slime

### ISSUE THREAD

**Issue by Resika0904** [O-n-y/oxy.mods#125]
Force updated today. Went to use the new Skewed map and was poking around at the world settings (except seed in this case), and realized that after the first change, the map was spawning traits that were disabled even with Specific settings. Which is generally a problem, but especially for that map lol.

**Comment by alishahb** [comment]
Please do follow steps in Troubleshooting: https://github.com/O-n-y/oxy.mods

and report your issue properly, so i can take a look

**Comment by O-n-y** [comment]
re iterated as https://github.com/O-n-y/oxy.mods/issues/126
