### ISSUE TITLE
Supplying / Tidying bug

### ISSUE THREAD

**Issue by Hubludo** [O-n-y/oxy.mods#131]
Hi Anna,
Supplying and Tidying Attributes produce bugs. 
If a Dupe has those two attributes, changing Tidying to another attribute (e.g. Decorating) makes the Supplying attribute value become 0. 
Reciprocally, changing Supplying to another attribute (e.g. Rocketry) makes the Tidying attribute value become 0. 
This bug is consistent and repeatable.
Take care meanwhile, and thank you again for your great mods.
ONI Version: 049-575720-5
Mods: DGSM only (no other mods running)
![Before 1](https://github.com/O-n-y/oxy.mods/assets/147387463/665aa16f-24ac-4322-837a-8f48e0aad15c)
![After 1](https://github.com/O-n-y/oxy.mods/assets/147387463/fb46fb00-72c1-4dff-8027-92ec1a60294d)
![Before 2](https://github.com/O-n-y/oxy.mods/assets/147387463/674f1253-c368-4684-9d80-07f9f8389701)
![After 2](https://github.com/O-n-y/oxy.mods/assets/147387463/107af186-82aa-4958-91c6-a769057664b9)

**Comment by O-n-y** [comment]
Thank you for the report! Will be fixed in next release 3.5.4.28+
Beta currently in testing via patrons.

More info and news about new release you can fnd in Discord
