### ISSUE TITLE
[DGSM] Crash on Frozen Friend awakening

### ISSUE THREAD

**Issue by aro-space** [O-n-y/oxy.mods#132]
OS: Windows 10 Home
Game Version Number: Build: U49-575720-SD
Mod Version: v3.4.40.10 1 (or v.1.0.1.322 viewed with Mod Manager)

Crash on attempting to defrost a duplicant on the linked teleporter world. 

[dgsm bug report.txt](https://github.com/O-n-y/oxy.mods/files/12849927/dgsm.bug.report.txt)
[DGSM Test.zip](https://github.com/O-n-y/oxy.mods/files/12849932/DGSM.Test.zip)

**Comment by O-n-y** [comment]
Thank you for the reporting! Will be fixed on next release 3.5.5.32+
Soon will be in beta for testing via Patrons 

More info and news about new release you can fnd in Discord

**Comment by O-n-y** [comment]
Fixed on last release build
