### ISSUE TITLE
Crash When Clicking 0n Choose a Blueprint from Printer, after 3rd Cycle 1st Print Available

### ISSUE THREAD

**Issue by dcasez** [O-n-y/oxy.mods#135]
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Ony.OxygenNotIncluded.DGSM2.MinionStartingStats_GenerateAttributes.Prefix (MinionStartingStats instance, System.Int32 pointsDelta, System.Collections.Generic.List1[T] disabled_chore_groups) (at <dd03bdd6c3974dfa8783a055fb4c56ae>:0)
(wrapper dynamic-method) MinionStartingStats.MinionStartingStats.GenerateAttributes_Patch1(MinionStartingStats,int,System.Collections.Generic.List1<ChoreGroup>)
MinionStartingStats.GenerateStats (System.String guaranteedAptitudeID, System.String guaranteedTraitID, System.Boolean isDebugMinion, System.Boolean is_starter_minion) (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
MinionStartingStats..ctor (System.Boolean is_starter_minion, System.String guaranteedAptitudeID, System.String guaranteedTraitID, System.Boolean isDebugMinion) (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
Ony.OxygenNotIncluded.DGSM2.CharacterContainer_GenerateCharacter.Prefix (CharacterContainer instance, MinionStartingStats& stats, KBatchedAnimController& animController, KToggle& selectButton, CharacterSelectionController& controller, System.Boolean is_starter, System.String guaranteedAptitudeID) (at <dd03bdd6c3974dfa8783a055fb4c56ae>:0)
(wrapper dynamic-method) CharacterContainer.CharacterContainer.GenerateCharacter_Patch1(CharacterContainer,bool,string)
CharacterContainer+<DelayedGeneration>d__47.MoveNext () (at <d1b7643456214f4e8c00f70e3a2b4469>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <72b60a3dd8cd4f12a155b761a1af9144>:0)

Build: U49-577063-V

dgsm is 3.6.2.16

**Comment by O-n-y** [comment]
Please make a proper issue, following guide:
https://github.com/O-n-y/oxy.mods

**Comment by O-n-y** [comment]
Closing this one for now, as no additiona information was provided
