### ISSUE TITLE
[Favorite Buildings] Pressing a number after Mop/Sweep/Dig/Destroy action key launches Build action 

### ISSUE THREAD

**Issue by ChristianMalazarte** [O-n-y/oxy.mods#138]
This is regarding the Key Binding mod.

So this has been a gripe of mine for many years. Setting a priority by pressing P then [number] works fine with this mod. I wish it would work the same way when pressing X + [number] to destroy, K + [number] to sweep, etc. Currently, when I press X + [number] it takes me out of destroy mode so I have to click the priority number manually.

I usually go X+9, or M+9, etc. and it's a habit that's hard to break.

**Comment by O-n-y** [comment]
Will be in next release build

The Mod will be inactive when tools selected: harvest, destory, sweep, mop
Tho it looks like with some of tools game do not allow to use keyboard to change priorities for some reason - including deconstruct, (maybe they would fix this on day).
