### ISSUE TITLE
The Mod Manager Mod 

### ISSUE THREAD

**Issue by DanielShively** [O-n-y/oxy.mods#139]
Here are The Like Logs And After It Crashed Idk, please fix it, Thanks: (ps the rest of the log dint copy to my clipboard and the bug won't happen again, tho it did happen 3 time, but i got some of it back so here:)
IOException: Sharing violation on path C:\Users\shive_ow6dxvx\OneDrive\Documents\Klei\OxygenNotIncluded\mods\config\1843965353\config.json
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper remoting-invoke-with-check)
Build: U50-581979-V

**Comment by O-n-y** [comment]
This issue not related to the mod, but to your security and access to the files from the game.
You should check your access rights C:\Users\shive_ow6dxvx\OneDrive\Documents\Klei\OxygenNotIncluded\mods for all inside folder. 
This issue could be related that you are using OneDrive
