### ISSUE TITLE
Debug Console troubles

### ISSUE THREAD

**Issue by Alaitoc** [O-n-y/oxy.mods#14]
When starting new game, after type of the game selected (survival or no sweat) nothing happens. Then when I look up mods menu game shows error message. Also I cannot load previously saved games. I use windows 10. Game has no issues with only this mod enabled. Mod version 1.0.0.7  Game version Automation update 399948. 

[save_files.zip](https://github.com/O-n-y/oxy.mods/files/4439742/save_files.zip)

**Comment by O-n-y** [comment]
Hi there!
Could not reproduce your issue, just loaded your game save files normally.

![image](https://user-images.githubusercontent.com/3432745/78598587-3cc1a400-7858-11ea-9503-a479a680fff5.png)

The error you have in this image https://imgur.com/a/lrqcumC

is from the other mod, which most likely change some biome settings or load some new game element - as an error come from loading biome data. (key duplicate for setting).

````
ProcGen.ComposableDictionary<Key,Value>
public void Merge(ComposableDictionary<Key, Value> other)
````

This error should exist withtout console (even tho you do not see it and it do not crash the game, there is still an error, which can affect the game), but i am not sure why this mod not crashing without console. 
Console itself just shows errors you have (not produce it).
I will check code, maybe in some place there was added some suppressor for such.

Purpose of console to make it easer for any user to track errors of other mod, if you have issue with those. So even if you regular user you should be able to use it to track for issues :-)

**Comment by O-n-y** [comment]
I removed profiler call (this is the only change from the original code), this won't remove error you have itself (as error as i said produced by other mod). but check if you still have a crash on 1.0.1.0

**Comment by Alaitoc** [comment]
Sadly i still have problem, guess i have to check mods affecting this one by one to figure which one is responsible, then ipdate if i find anything

**Comment by O-n-y** [comment]
> Sadly i still have problem.
> Edit: so following mods are incompatible - Neon Eden, Roller Snakes, Empty Worlds, I Love Slicksters - Morphs.
I will check those.
Msot likely those are not incompatible, but causing errors (which without console do not crash but do crash with it - when it outputing error).

**Comment by O-n-y** [comment]
Please tryout version 1.0.2.1

**Comment by Alaitoc** [comment]
Now it runs without errors.
P.S. Thank you very much for your hard work on the ONI mods.

**Comment by O-n-y** [comment]
Great to hear! :-)
