### ISSUE TITLE
[DGSM] CN UI translation

### ISSUE THREAD

**Issue by taozhiyu** [O-n-y/oxy.mods#143]
The translation of the text in the settings is not finished, and I can help with translation to Simplified Chinese.

You can use translation assistance tools such as sharing translated json files on github or using crowdin.com (recommended).

**Comment by O-n-y** [comment]
Feel free to update the current version of localization:

[TranslationCn.zip](https://github.com/O-n-y/oxy.mods/files/13705859/TranslationCn.zip)

**Comment by taozhiyu** [comment]
1. new TranslationCN here: [TranslationCn.zip](https://github.com/O-n-y/oxy.mods/files/13714383/TranslationCn.zip)
   - fix translation mistakes
   - add missing translation

2. There seems still have some untranslatable phrases. e.g. :

<details><summary>Screenshots</summary>

![image](https://github.com/O-n-y/oxy.mods/assets/49258735/51d81b7c-2dfd-40ac-8f8d-d0b740bf79d0)

![image](https://github.com/O-n-y/oxy.mods/assets/49258735/236451eb-b391-4a3e-905b-d89ce7d7f61d)

![image](https://github.com/O-n-y/oxy.mods/assets/49258735/9b547bb6-b4f2-4461-aafb-55027e2a95d9)

![image](https://github.com/O-n-y/oxy.mods/assets/49258735/49f15f77-1364-4721-9320-7db6552af6f7)
</details>

These words are in-built, so that unable to translate.

And the time format seems to be more like `YYYY-MM-DD` instead of `DD-MM-YYYY`, it would be best if slots could be used to allow translation.

3. I also found a BUG: click one `Duplicant setting` btn, and click another one without closing(or apply) this one, after close any window and then try to change(or close or apply), it crashes.

https://github.com/O-n-y/oxy.mods/assets/49258735/511406b1-a9cd-4921-b416-ba276438b768

Anyway, great crafts!!


PS: 
Translating with zip files seems too stupid and not very easy to update strings in time, and would you mind to update the translation files, like Klei: https://github.com/kleientertainment/KleiAccountsLocale (maybe in this repo is well enough).

so that I(as well as whoever would like to make contribute) can subscribe it, and make PRs easily.

**Comment by O-n-y** [comment]
The time format is: DD.MM.YYYY

**Comment by O-n-y** [comment]
For more translation
[TranslationCn.zip](https://github.com/O-n-y/oxy.mods/files/13717333/TranslationCn.zip)

**Comment by taozhiyu** [comment]
> For more translation [TranslationCn.zip](https://github.com/O-n-y/oxy.mods/files/13717333/TranslationCn.zip)

I tried to start the translation, but could you please attach the translationEn file?

I've checked the Steam Workshop, but the files have not been released.

I'm not sure what the text should be.

**Comment by O-n-y** [comment]
[TranslationEn.zip](https://github.com/O-n-y/oxy.mods/files/13723376/TranslationEn.zip)
Sure, sorry :)

**Comment by taozhiyu** [comment]
Done, 👍 

[TranslationCn(V3).zip](https://github.com/O-n-y/oxy.mods/files/13723879/TranslationCn.V3.zip)

**Comment by taozhiyu** [comment]
Hi, glad the mod is compatible with the latest DLC3 and adds some new features.

And at the same time the localisation needs to be updated, it would be easier to use a tool like crowdin (email alerts for updates to the original strings, and we can focus on translations).

![image](https://github.com/user-attachments/assets/2adf5478-cf4a-42cd-b02c-7428109fe36b)

Hope to hear from you soon 😃

**Comment by taozhiyu** [comment]
Or just send the file with Chinese and English (over and over again)

**Comment by O-n-y** [comment]
Do you have Discord, if possible PM me, thank you!
[Localization.zip](https://github.com/user-attachments/files/16402454/Localization.zip)

**Comment by taozhiyu** [comment]
> Do you have Discord, if possible PM me, thank you! [Localization.zip](https://github.com/user-attachments/files/16402454/Localization.zip)

Yes, but unfortunately the use of discord is not supported in my region (VPN required).

So I can't receive messages in time 😢 

PS: new file here: [TranslationCn-28.07.24.zip](https://github.com/user-attachments/files/16402506/TranslationCn-28.07.24.zip)

**Comment by taozhiyu** [comment]
Sorry for reopen again...
some items can not be found in translation file
![image](https://github.com/user-attachments/assets/8cc4a0d1-cf09-40fd-a3bb-ff57d80a751f)
![image](https://github.com/user-attachments/assets/5c5d9c26-5a68-448a-85c6-e0e85b49fe49)

![image](https://github.com/user-attachments/assets/ddf68926-938e-4e62-92a0-98d1e79161ba)


By the way, I see some strings in the translation file, like : `SELECT_LONE_WOLF`, `SELECT_TEAM`, etc.
But it still seems to be `select 3 duplicants, ready to start` with only one signle duplicant.( translated from Chinese string on screen, unverified).

![image](https://github.com/user-attachments/assets/b56610c2-2872-4148-9622-2559f11d1ee9)

**Comment by O-n-y** [comment]
i will check out and resend you the file!
