### ISSUE TITLE
Crashing on Loading

### ISSUE THREAD

**Issue by Sol7721** [O-n-y/oxy.mods#144]
MissingFieldException: Field 'KMod.Mod.file_source' not found.

Ony.OxygenNotIncluded.ModManager.Updater.UpdateAuthorsInfo (System.Collections.Generic.HashSet`1[T] updateAuthors, System.Boolean threadPool) (at <bc7fe753ca3f420aa048c2afbc3bf54c>:0)
Ony.OxygenNotIncluded.ModManager.SteamUGCService_OnSteamUGCQueryDetailsCompleted.Postfix (Steamworks.SteamUGCQueryCompleted_t pCallback, System.Boolean bIOFailure, System.Collections.Generic.HashSet`1[T] ___publishes) (at <bc7fe753ca3f420aa048c2afbc3bf54c>:0)
(wrapper dynamic-method) SteamUGCService.SteamUGCService.OnSteamUGCQueryDetailsCompleted_Patch1(SteamUGCService,Steamworks.SteamUGCQueryCompleted_t,bool)
Steamworks.CallResult`1[T].OnRunCallResult (System.IntPtr pvParam, System.Boolean bFailed, System.UInt64 hSteamAPICall_) (at <265662ccba5f4b45b650e9f26e9148fe>:0)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception)
Steamworks.CallResult`1:OnRunCallResult(IntPtr, Boolean, UInt64)
Steamworks.CallbackDispatcher:RunFrame(Boolean)
Steamworks.SteamAPI:RunCallbacks()
SteamManager:Update()

Build: U50-587362-S

**Comment by Sol7721** [comment]
This happens even when loading the mod alone. Thank you for any help!

**Comment by O-n-y** [comment]
You have an outdated version, please do follow guide on Steam mod page or in my Discord for help how to force update

**Comment by O-n-y** [comment]
nope, correct version:  **Mod Manager 2.2.1.34** 

Please read mod page description - there will be Throubleshouting section and also you can find #guides channel on my Discord as well, which should help you https://discord.com/channels/611802435220144148/612697981740777494

**Comment by Sol7721** [comment]
I wasn't referring to the mod manager, I was referring to the butcher station mod.
________________________________

**Comment by Sol7721** [comment]
but thanks for the help anyways. If i get the time to hunt down all of this toubleshooting someday I'll check it out.
________________________________

**Comment by O-n-y** [comment]
i can't tell anything about other mods, sorry

**Comment by O-n-y** [comment]
you can try force update button, but can be the mod you are talking about just not updated to the last version of the game
