### ISSUE TITLE
[Mod Manager] ONI Crashes on Startup with Mod manager enabled

### ISSUE THREAD

**Issue by Mord0rN** [O-n-y/oxy.mods#145]
The OS you are running.
 - Microsoft Windows 11 Pro
 - Version	10.0.22621 Build 22621

    The games version number.
- Build: U50-587362-SD

    !!! Provide mod version you have
- Mod Manager 2.2.1.34

    Describe your problem.
- Game crashes on startup with the mod enabled
- 
    Describe how to reproduce it.
- Starting the game with Mod Manager enabled

**Comment by O-n-y** [comment]
Try to disable other mods, would it still be issue ?
If so, install my other mod: DebugConsole and run with it, copy log from it and provide it

**Comment by Mord0rN** [comment]
<img width="1184" alt="image" src="https://github.com/O-n-y/oxy.mods/assets/34132608/b26c66d4-8ce4-49f3-88c7-a6744ac052d6">
This happened before, after Restarting the PC several times, and disabling then enableing, then disabling all mods aside from the manager, now it works. After every toggle i restarted my system.

**Comment by O-n-y** [comment]
then it might be some other mod causing the issue - you should click "more info" when such happen or use my advice about DebugConsole, which would help to know what exactly the cause of the situation
