### ISSUE TITLE
[DGSM] 3.6.7.37 Duplicant personalities not available with new colony. 

### ISSUE THREAD

**Issue by jeatkins09** [O-n-y/oxy.mods#149]
OS: Windows 11
Game Version: U50-587362-SD
Mod Version: 3.6.7.37

"Unlock All Duplicant Personalities for Starting crew choice" is checked, however after re-rolling for over an hour none of the locked personalities was given as a choice. This was done on a new save file with only Mod Manager and DGSM active. 

![Mod List](https://github.com/O-n-y/oxy.mods/assets/116019656/fa3c5029-5cbc-45e7-bcad-07d9572954b4)
![Mod Settings](https://github.com/O-n-y/oxy.mods/assets/116019656/2d8884a2-07ce-4ad2-a00c-bb527ade048e)

**Comment by O-n-y** [comment]
should be fixed on umpcoming 3.7 (currently in BETA testing via Patrons), more infor in Discord
