### ISSUE TITLE
NoDrop: Index was out of range // FixedUpdate

### ISSUE THREAD

**Issue by Killface1980** [O-n-y/oxy.mods#15]
Thank you for this mod, it's essential.
After playing for a long time, ONI crashed with this message

```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <e1319b7195c343e79b385cd3aa43f5dc>:0
at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0
at System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) [0x00009] in <e1319b7195c343e79b385cd3aa43f5dc>:0
at Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () [0x0020c] in <dd00e5767eaa43ab96216cee53dbcbfe>:0
```

No idea what happened exactly, my colony has 15 dupes and I couldn't track it down any further.
[output_log.txt](https://github.com/O-n-y/oxy.mods/files/4532448/output_log.txt)

**Comment by O-n-y** [comment]
Provide information which version of mod you have, you can get it by using my other mod: Mod Manager

**Comment by Killface1980** [comment]
It's the current Steam version from 2019-12-23.
I'll report the version number once I'm back to ONI. In the mean time I've played extendively and haven't encountered the bug again.

**Comment by O-n-y** [comment]
Was asking about mod version, checkout starting page for how to report issue: 
https://github.com/O-n-y/oxy.mods

**Comment by O-n-y** [comment]
btw steam version can't be from 2019-12-23, game was updated many times after this :-)

**Comment by Killface1980** [comment]
I'll check for the proper version.
According to the Steam changelog, there haven't been updates since
December. The changelog is normally pretty reliable, maybe it hasn't
updated?
.
https://steamcommunity.com/sharedfiles/filedetails/changelog/1868454866

Am Sa., 2. Mai 2020 um 11:44 Uhr schrieb O-n-y <notifications@github.com>:

**Comment by O-n-y** [comment]
change log - yes, steam cache - no (can give you outdated version), unless you are using for example my Mod Manager, which keeps mods really up to date and alsow shows mod version.

**Comment by O-n-y** [comment]
`It's the current Steam version from 2019-12-23.` your message was not clear i though you talking about game versiom. 
But anyway you should never rely on any dates and only count on version acutal numbers to check if those are actual. Update date do not say which version you actually have.

**Comment by O-n-y** [comment]
closed as more information never provided
