### ISSUE TITLE
[DGSM] Game Crashes upon Opening Dupe Customization Menu

### ISSUE THREAD

**Issue by EATZYOWAFFLEZ** [O-n-y/oxy.mods#150]
Upon creating a world, trying to customize the starting dupes instantly crashes the game. Rerolling or selecting a class type for the dupes does not crash the game.

I made sure my game was updated to the latest version, I updated the mod to the latest version, and I tried all of this with no other mods enabled.

**Comment by O-n-y** [comment]
https://github.com/O-n-y/oxy.mods
please do create issue using information from How to Report Bugs

**Comment by O-n-y** [comment]
closing as no more info provided, also i suggest to take a look at this ticket 
https://github.com/O-n-y/oxy.mods/issues/151
