### ISSUE TITLE
[DGSM] Duplicants Generation Settings Manager Crashing Game When Starting New World

### ISSUE THREAD

**Issue by BomberBabe94** [O-n-y/oxy.mods#154]
OS: Windows 10
Game Version: U51-597172-V
Mod Version: 3.4.40.104
Trying to start a new world, every time I click on the cog icon to change any of the traits of the dupe the entire game crashes without the edit window opening. I can cycle through the dupes endlessly without crashing, but trying to edit them kills the game. The only mods active are this one, as well as your mod manager and debug console.
I have the info from the debug console pasted below, the first line says 'missing method exception: void', not that I know what that means.

[DebugConsole][1]: Error[Exception]: MissingMethodException: void CollapsibleDetailContentPanel.SetLabelWithButton(string,string,string,string,string,System.Action)
Ony.OxygenNotIncluded.DGSM.EditableTitleBar_OnSpawn+<>c__DisplayClass0_0.<Postfix>b__0 () (at <1a3f7646dc054547a38cc0daf9ff0db3>:0)
KButton.SignalClick (KKeyCode btn) (at <3ca21dc18eae422d87255277091f8593>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3ca21dc18eae422d87255277091f8593>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by O-n-y** [comment]
This is outdated version. Actual version:  3.6.7.37

**Comment by BomberBabe94** [comment]
Everything is saying it's up to date?? Anyway to force an update then??

**Comment by O-n-y** [comment]
Please do checkout Throubleshooting section of the mod.
This is sadly the Steam cache issue, not the mod itself.

**Comment by O-n-y** [comment]
You can try force update using my other mod - Mod Manager, also i recommend to checkout #guides section in my Discord
