### ISSUE TITLE
DGSM Crashes when trying new game

### ISSUE THREAD

**Issue by bmp416** [O-n-y/oxy.mods#156]
Game version: U51-600112-5
Mod Version: 3.6.7.37
OS: Windows 11

Everytime I try to start a new game, and got o click on the gear icon to change my dupes traits, the game crashes everytime. I have turned off every mod but DGSM and Mod manager and it happens everytime.

Error Message below:

MissingMethodException: void CollapsibleDetailContentPanel.SetLabelWithButton(string,string,string,string,string,System.Action)

Ony.OxygenNotIncluded.DGSM.EditableTitleBar_OnSpawn+<>c__DisplayClass0_0.<Postfix>b__0 () (at <8890eb6a31a24a9ba37d19a271a72970>:0)
KButton.SignalClick (KKeyCode btn) (at <3ca21dc18eae422d87255277091f8593>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3ca21dc18eae422d87255277091f8593>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U51-600112-S

**Comment by O-n-y** [comment]
You have issue with cache - steam loading outdated version for you (this is not a mod issue)
Check out how other user solved it: https://github.com/O-n-y/oxy.mods/issues/151#issuecomment-1997774979
