### ISSUE TITLE
[DGSM] 3.4.41.135 Crash when trying to edit duplicant on new game Base game

### ISSUE THREAD

**Issue by Kjhendir** [O-n-y/oxy.mods#158]
OS: Windows 10
Build version: U51-600112-V
Mod Version: 3.4.41.135

The game crashes when I click "Duplicant Configuration" every single time, my currently active mods are DGSM 3.4.41.135, Mod Manager 2.2.1.34 and Debug Console 1.0.7.45

How to reproduce the problem:
Click New Game
Create any world
Click on Duplicant Configuration
Crash

The crash screen shows this text on more detail
`MissingMethodException: void CollapsibleDetailContentPanel.SetLabelWithButton(string,string,string,string,string,System.Action)

Ony.OxygenNotIncluded.DGSM.EditableTitleBar_OnSpawn+<>c__DisplayClass0_0.<Postfix>b__0 () (at <8890eb6a31a24a9ba37d19a271a72970>:0)
KButton.SignalClick (KKeyCode btn) (at <3ca21dc18eae422d87255277091f8593>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3ca21dc18eae422d87255277091f8593>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U51-600112-V`

And the Debug Console shows this text in red
`[DebugConsole][1]: Error[Exception]: MissingMethodException: void CollapsibleDetailContentPanel.SetLabelWithButton(string,string,string,string,string,System.Action)
Ony.OxygenNotIncluded.DGSM.EditableTitleBar_OnSpawn+<>c__DisplayClass0_0.<Postfix>b__0 () (at <8890eb6a31a24a9ba37d19a271a72970>:0)
KButton.SignalClick (KKeyCode btn) (at <3ca21dc18eae422d87255277091f8593>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3ca21dc18eae422d87255277091f8593>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

  [DebugConsole][1]: Error[Exception]: MissingMethodException: void CollapsibleDetailContentPanel.SetLabelWithButton(string,string,string,string,string,System.Action)
Ony.OxygenNotIncluded.DGSM.EditableTitleBar_OnSpawn+<>c__DisplayClass0_0.<Postfix>b__0 () (at <8890eb6a31a24a9ba37d19a271a72970>:0)
KButton.SignalClick (KKeyCode btn) (at <3ca21dc18eae422d87255277091f8593>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3ca21dc18eae422d87255277091f8593>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()`

**Comment by O-n-y** [comment]
you have an outdated version, last one: 3.6.7.37
