### ISSUE TITLE
[DGSM] 3.4.41.135 Game immediately crashes after I click on the cog to use the mod.

### ISSUE THREAD

**Issue by Sharktail100** [O-n-y/oxy.mods#159]
**OS: Windows 11
Game Version: U51-600112-VD
Mod Version: 3.4.41.135**

When I start a new game, I click on the cog above the dupe to use mod, it then crashes immediately. 

I've reset my mod cache, I've disabled all other mods other than DGSM, I've now made a report. I don't have a save file for obvious  reasons.

Did I do something wrong?

**Crash Report**
```
MissingMethodException: void CollapsibleDetailContentPanel.SetLabelWithButton(string,string,string,string,string,System.Action)

Ony.OxygenNotIncluded.DGSM.EditableTitleBar_OnSpawn+<>c__DisplayClass0_0.<Postfix>b__0 () (at <8890eb6a31a24a9ba37d19a271a72970>:0)
KButton.SignalClick (KKeyCode btn) (at <3ca21dc18eae422d87255277091f8593>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3ca21dc18eae422d87255277091f8593>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U51-600112-VD
```

**Comment by O-n-y** [comment]
You have an outdated version of the mod.
The last version is:  to 3.6.7.37

**Comment by O-n-y** [comment]
Please do follow Throubleshooting on the mod page, 
alternatively you can checkout #guides channel on my discord(https://discord.gg/CSF6Rzez8H) and also install my other mod Mod Manager, which could help resolving this issue

**Comment by Sharktail100** [comment]
> You have an outdated version of the mod. The last version is: to 3.6.7.37

I Just force updated DGSM and it is still giving me problems
