### ISSUE TITLE
[DGSM] 3.6.7.37 Game Encounters an error when selecting Gear Icon at the start of a new game in selecting dupes

### ISSUE THREAD

**Issue by 98kazer** [O-n-y/oxy.mods#161]
OS: Windows 10 Pro
Build: U51-600112-S
Mod Version:  3.6.7.37

DGSM 3.6.7.37

already tried File integrity fix in steam, doesn't work

how my problem starts:
Game start > Select New Game > Select Survival > Select Classic > [no changes in settings] Start Game 
> Select any Duplicant Configuration [gear Icon] > Game encounters an error
 
No Save file Since error starts at dupe selection screen where I can't save

Error Info:
MissingMethodException: void CollapsibleDetailContentPanel.SetLabelWithButton(string,string,string,string,string,System.Action)

Ony.OxygenNotIncluded.DGSM.EditableTitleBar_OnSpawn+<>c__DisplayClass0_0.<Postfix>b__0 () (at <8890eb6a31a24a9ba37d19a271a72970>:0)
KButton.SignalClick (KKeyCode btn) (at <3ca21dc18eae422d87255277091f8593>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3ca21dc18eae422d87255277091f8593>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U51-600112-S

![oni](https://github.com/O-n-y/oxy.mods/assets/168797159/da433267-6a5e-49d5-a9f3-9cb6338e17b0)

**Comment by O-n-y** [comment]
from the log you provided - this is an outdated version. this is not the actual version is: 3.6.7.37 (as if it was - there would be no such error).
this is issue with the steam cache, not the mod.

you can find how to solve this issue in can use in guides channel (https://discord.com/channels/611802435220144148/612697981740777494) of my Discord (https://discord.gg/hhetzbVyAW) channel, also there are tips in Thtoubleshooting section of the mod.




"
_**Tip from some user (Solving Steam Cache issue):**_ 
`
Hello all, I recently have been trying to get back to playing ONI, but I was experiencing similar issues like everyone else. I highly recommend going the drastic route if you are having issues
Back up all saves either manually or save to cloud
Back up all mods either manually or favorite steam mods
Uninstall the game through steam
Delete all Oxygen Not Included folders in all Klei folders
A. AppData/LocalLow/Klei/Oxygen Not Included
B. Documents/Klei/Oxygen Not Included

Reinstall the Game, Verify Integrity as a safety measure
Run the game, verify it still runs
Install your mods from here. I highly recommend the installing the Mod Manager and Debug Console by Ony first, run the game, and install more as needed`

_The game seems to have resolved all issues including the clicking on the gear icon problem. I hope this helps_ "
