### ISSUE TITLE
[DGSM] Feature Request - World trait Frozen Friend

### ISSUE THREAD

**Issue by AMalleus** [O-n-y/oxy.mods#163]
There is world trait which is called Frozen Friend. 
There is cryochamber which you may open and new dupe will join you. Maybe you could add a possibility to modifiy dupe settings? Just because you can modify everything about dupe settings in the whole game but not only this one.

**Comment by O-n-y** [comment]
i do add stuff, which exist in the game, not in other mods
sorry

**Comment by AMalleus** [comment]
Spaced Out official DLC = other mod for you? Ok then, no problem :)

**Comment by O-n-y** [comment]
The other mod - is " world mod which is called Frozen Friend."
maybe i missunderstood what you mean

**Comment by O-n-y** [comment]
Then please, do explain it properly, with screenshot would be best

**Comment by AMalleus** [comment]
As said from beginning... There is Cryotanks around the world which has Dupe inside it. Mostly it comes from world Trait Frozen Friend. When you open it then new Dupe joins your colony. I would like to have a possibility to modify its settings.
Maybe you could add some hook for event on new dupe appear from Cryotank in code. Which will allow then to open up your mode window to modify this new Dupe.

![image](https://github.com/O-n-y/oxy.mods/assets/24564437/a3c14a0c-179c-48f6-a05b-eeccb6897bad)
![image](https://github.com/O-n-y/oxy.mods/assets/24564437/db6b37c8-1a4d-4566-b806-d5c02c108661)

**Comment by O-n-y** [comment]
Can you provide save file with this Cryo tank, i will check out

**Comment by Sgt-Imalas** [comment]
@AMalleus fyi, the mod "Duplicant Stat Selector" has that feature (https://steamcommunity.com/sharedfiles/filedetails/?id=2856555858)

**Comment by O-n-y** [comment]
closing this by now, as no save file provided
