### ISSUE TITLE
[DGSM] 3.6.7.37 MissingMethodException: void CollapsibleDetailContentPanel.SetLabelWithButton

### ISSUE THREAD

**Issue by vk65535** [O-n-y/oxy.mods#164]
Windows 10
U51-600112-S
3.6.7.37

![image](https://github.com/O-n-y/oxy.mods/assets/6334811/f6ed512b-e880-4a25-a528-8a7f1b6c63e3)

MissingMethodException: void CollapsibleDetailContentPanel.SetLabelWithButton(string,string,string,string,string,System.Action)

Ony.OxygenNotIncluded.DGSM.EditableTitleBar_OnSpawn+<>c__DisplayClass0_0.<Postfix>b__0 () (at <8890eb6a31a24a9ba37d19a271a72970>:0)
KButton.SignalClick (KKeyCode btn) (at <3ca21dc18eae422d87255277091f8593>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3ca21dc18eae422d87255277091f8593>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U51-600112-S

**Comment by O-n-y** [comment]
this mean you have an outdated version of the mod. if you sure you don't
then checkout this comment: https://github.com/O-n-y/oxy.mods/issues/151#issuecomment-1997774979
