### ISSUE TITLE
Game always crashes when creating a new game, at the duplicanr rolling screen

### ISSUE THREAD

**Issue by techurbana** [O-n-y/oxy.mods#168]
Having only the DGSM mod active, and having DGSM mod config as default (tested several mod config, anyway), the game **always** crashes at the duplicant rolling screen, when creating a new game.  Several asteroid tested.  Tested in Ubuntu 23.10 native and also forcing proton usage with same results.  No DLCs installed.

DGSM Mod version is latest (used update manager) mod: 3.6.7.27

The following message appear:
---------------------------------------------------------------------
NullReferenceException: Object reference not set to an instance of an object

Ony.OxygenNotIncluded.Object_Extensions.InvokePrivateMethod[T] (System.Object obj, System.String methodName, System.Object[] pars) (at <5ec6cc0b79ef4c8ca505acc27715c91b>:0)
Ony.OxygenNotIncluded.DGSM2.CharacterContainer_GenerateCharacter.Prefix (CharacterContainer __instance, MinionStartingStats& ___stats, KBatchedAnimController& ___animController, KToggle& ___selectButton, CharacterSelectionController& ___controller, System.Boolean is_starter, System.String guaranteedAptitudeID) (at <5ec6cc0b79ef4c8ca505acc27715c91b>:0)
(wrapper dynamic-method) CharacterContainer.CharacterContainer.GenerateCharacter_Patch1(CharacterContainer,bool,string)
CharacterContainer+<DelayedGeneration>d__47.MoveNext () (at <043309e6f0914d9f9e207a782760f195>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <72b60a3dd8cd4f12a155b761a1af9144>:0)

Build: U52-622509-V

**Comment by MudMan6996** [comment]
I keep getting the same error at the same point as well.

**Comment by O-n-y** [comment]
DGSM is currently in **BETA testing** via patrons, if all goes well - the release version is planned to come to Steam in Monday!
All news in Discord: https://discord.com/channels/611802435220144148/611970308706009107

**Comment by O-n-y** [comment]
released on steam
