### ISSUE TITLE
[Research Manager] v1.3.1.6 - Crash when submitting module in the Research Portal (Frosty Planet Pack)

### ISSUE THREAD

**Issue by ashugar** [O-n-y/oxy.mods#170]
[The Underground Tunnel Cycle 10.zip](https://github.com/user-attachments/files/16325557/The.Underground.Tunnel.Cycle.10.zip)
Hi! I'm aware you're already in the middle of working on updates for the new DLC, just wanted to get this on the list in case it was missed (I didn't see Research Manager listed for updates anywhere on Discord).

OS: Win 11
Game Version: Build: U52-622509-SC
Mod Version: 1.3.1.6

When doing the "Unlock Research" action of the Research Portal, at the end of the process the dup submits a module to the Research Portal and a new research item is supposed to unlock. If you have Research Manager enabled when this occurs, you get the following error:
InvalidCastException: Specified cast is not valid.

Ony.OxygenNotIncluded.ResearchManager.ResearchScreen_OnResearchComplete.Prefix (ResearchScreen __instance, System.Object data) (at <c993d3d1d74e4367b6fbb402781761d1>:0)
(wrapper dynamic-method) ResearchScreen.ResearchScreen.OnResearchComplete_Patch2(ResearchScreen,object)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <3a2e13ca97c146c4b5d2f735a443e5e3>:0)
KMonoBehaviour.Trigger (System.Int32 hash, System.Object data) (at <3a2e13ca97c146c4b5d2f735a443e5e3>:0)
TechInstance.UnlockPOITech (System.String tech_id) (at <043309e6f0914d9f9e207a782760f195>:0)
TechItem.POIUnlocked () (at <043309e6f0914d9f9e207a782760f195>:0)
POITechItemUnlocks+Instance.UnlockTechItems () (at <043309e6f0914d9f9e207a782760f195>:0)
POITechItemUnlockWorkable.OnCompleteWork (Worker worker) (at <043309e6f0914d9f9e207a782760f195>:0)
Workable.CompleteWork (Worker worker) (at <043309e6f0914d9f9e207a782760f195>:0)
Worker.CompleteWork () (at <043309e6f0914d9f9e207a782760f195>:0)
Worker.Work (System.Single dt) (at <043309e6f0914d9f9e207a782760f195>:0)
GameStateMachine`4+State+<>c__DisplayClass88_0[StateMachineType,StateMachineInstanceType,MasterType,DefType].<ToggleWork>b__1 (StateMachineInstanceType smi, System.Single dt) (at <043309e6f0914d9f9e207a782760f195>:0)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <3a2e13ca97c146c4b5d2f735a443e5e3>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <3a2e13ca97c146c4b5d2f735a443e5e3>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <3a2e13ca97c146c4b5d2f735a443e5e3>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <3a2e13ca97c146c4b5d2f735a443e5e3>:0)
Game.SimEveryTick (System.Single dt) (at <043309e6f0914d9f9e207a782760f195>:0)
Game.Update () (at <043309e6f0914d9f9e207a782760f195>:0)

Build: U52-622509-SC

To reproduce:
Start a game and explore until you find the Research Portal, then activate it with Research Manager enabled. With or without research in queue.

Submitted save file that's close to the Research Portal for activation.

**Comment by O-n-y** [comment]
fixed on next release build
