### ISSUE TITLE
[WGSM] - Config resetting

### ISSUE THREAD

**Issue by FilipePfluck** [O-n-y/oxy.mods#171]
when I open "game settings" and change something, all the configuration I've made in WGSM is resetted

![image](https://github.com/user-attachments/assets/bfec92df-c804-4cc8-a4f4-ed7f010a76a6)
![image](https://github.com/user-attachments/assets/73df27aa-1cf8-4b0f-ac51-e37db20d9a3e)

in the first screenshot, I've configured the first asteroid to have metal rich. Then, I opened "game settings" and checked the "sandbox" checkbox. Then after closing the game settings, all my config in WGSM was lost. 

I'm not sure if this is intended, but it is kinda annoying so I'm reporting it

**Comment by O-n-y** [comment]
will be checking it, thank you for the report!

**Comment by O-n-y** [comment]
will be fixed in upcoming release version

Join Discord for more news: https://discord.gg/hhetzbVyAW
