### ISSUE TITLE
[DGSM] v3.7.0.167 Crash when the numer of interest be set to 0

### ISSUE THREAD

**Issue by nullpo21** [O-n-y/oxy.mods#172]
The mod will going to crash when the numer of interest be set to 0 with the new DLC's map.

![Snipaste_2024-07-23_11-53-21](https://github.com/user-attachments/assets/e41130e5-276f-4951-a504-0f3c1dc4e65c)
![Snipaste_2024-07-23_11-54-30](https://github.com/user-attachments/assets/4e226750-884c-4075-9381-c2732e2855b3)

**Comment by O-n-y** [comment]
Thank you for the reporting, i will checking it out!

Join Discord for all news: https://discord.gg/hhetzbVyAW

**Comment by O-n-y** [comment]
was it before generating 0 interests for you? 
can you attach the log from Debug Console?

**Comment by O-n-y** [comment]
i could not manage to get a crash

**Comment by O-n-y** [comment]
![image](https://github.com/user-attachments/assets/d4333e0c-6a7d-4708-adbb-a9dd829d26f1)
![image](https://github.com/user-attachments/assets/41357c6a-801b-4f7e-9ffc-67c09d25649d)
most likele you have crush from some other mod, which intersept DGSM

try disable other similar mods.

Use my other mod *MPOrganizer*: https://steamcommunity.com/sharedfiles/filedetails/?id=3284635963
save current mods list as preset (so you could easily restore it later). 
disable all mods, but not mine - run the game and check if you would have a crash

if you would be able to share more information of how to reproduce this problem, i will be happy too

**Comment by nullpo21** [comment]
Thank you for your reply.
Following your prompt, I turned off all other mods except DGSM and then tested again. But the result is still the same.
It will crashing when the '固定兴趣数量' is ON and the number of  '固定兴趣数量' be set to 0.

I've recorded a video and I contacted you from discord.

**Comment by Michael-YMCA** [comment]
I had a similar problem and it also happened when I only started a mod I tried reinstalling the game and clearing the mod config files
![Uploading 未标题-1.png…]()

**Comment by Michael-YMCA** [comment]
I had a similar problem and it also happened when I only started a mod I tried reinstalling the game and clearing the mod config files
![未标题-1](https://github.com/user-attachments/assets/8569902b-88cf-4b0e-9b4f-7245c056f3a4)

**Comment by Michael-YMCA** [comment]
Unlike nullpo21, the module settings do not affect the error message no matter how I check them

**Comment by O-n-y** [comment]
fixed on next release
