### ISSUE TITLE
[WGSM] Version: 3.0.1.127. Oil traits doesnt work for spaced out -> new frosty planet

### ISSUE THREAD

**Issue by klienjoy** [O-n-y/oxy.mods#173]
If you're trying to create a new spaced out -> frosty planet you can't select any of oil traits. For all other planets it works. I used to  have an oil biome at the bottom of the planet ( above the magma, instead of useless empty space ) :) 

Please have a look
<img width="433" alt="image" src="https://github.com/user-attachments/assets/b1c21dd6-ee64-4be8-ad8c-b9a30f5205db">
<img width="503" alt="image" src="https://github.com/user-attachments/assets/869c0009-374c-44dd-9cba-8b181b30b70f">

Also, if you tab to the different view or click "game settings" during the planet selection -> all your selected traits will reset :)

**Comment by O-n-y** [comment]
I will check this out, thank you!

Join Discord for all news: https://discord.gg/hhetzbVyAW

**Comment by O-n-y** [comment]
it looks like be default they do not allow oil trait in this planet, i will see if anything could be done about it

**Comment by O-n-y** [comment]
Trait rules for: STRINGS.WORLDS.CERESSPACEDOUT.NAME
				forbiddenTag: Surface
				forbiddenTag: Oil
				forbiddenTag: NonStartWorld
				forbiddenTrait: traits/GeoDormant
				forbiddenTrait: traits/MagmaVents

**Comment by klienjoy** [comment]
That's fine, we can close the thread <3

**Comment by O-n-y** [comment]
in next version it won't propose those traits which are not allowed for the asteroid to not confuse people :)

**Comment by O-n-y** [comment]
have you ever managed to generate frosty planet  with oild traits before?

**Comment by klienjoy** [comment]
No, it's a new planetoid from frosty DLC

**Comment by O-n-y** [comment]
тогда я вас не правильно поняла - подумала, что раньше у вас они нормально генерились :)

**Comment by klienjoy** [comment]
Нет, любые другие начальные планетойды из категории spaced out генерировались с нефтью с Вашим замечательным модом :-)

**Comment by O-n-y** [comment]
![image](https://github.com/user-attachments/assets/3d8af761-747b-4ef7-a662-0ae3c1e39006)

**Comment by O-n-y** [comment]
будет в следующем релизе :-)
