### ISSUE TITLE
WGSM suppressing mandatory CO2 geyser on Frosty Planet Pack

### ISSUE THREAD

**Issue by kyndigen** [O-n-y/oxy.mods#180]
I know some asteroid types have mandatory geysers that will always be present.  For example, on Terra, there should always be a cool steam vent not too far from the start.  With the new Frosty Planet Pack, Oxygen production comes via the new plant (Alveo Vera) which produces Oxylite from Carbon Dioxide, and the mandatory vent type changes from cool steam to carbon dioxide.

Steps to reproduce:

Start a no-mod game with seed CER-A-706701914-PJA9M-D3-0.  There will be a CO2 vent on the left-hand side of the map, about 3/4 of the way to the top, near a large copper geode.

Start the same seed with WGSM enabled.  Use WGSM to remove Geodormant, and add Geoactive and Metal Rich.  There will be various vents and volcanos in the same area, but no CO2 vent on the entire map.
 
OS: MacOS 14.6.1
ONI: U52-626616 (Frosty Planet Pack Installed, Spaced Out DISABLED)
WGSM: 3.0.3.141
Game seed: CER-A-706701914-PJA9M-D3-0

**Comment by O-n-y** [comment]
this is not a bug, the WGSM itself do not generate geyser or anything else. All generation is done by game itself, WGSM is only control traits which game will use.
As for the Frosen asteroid, the way to make oxygen: use salt geyser, desalinator and then Electrolyzer to generate oxygen.
