### ISSUE TITLE
使用mod创建新存档是崩溃

### ISSUE THREAD

**Issue by Z2935826653** [O-n-y/oxy.mods#182]
NullReferenceException: Object reference not set to an instance of an object

Ony.OxygenNotIncluded.Object_Extensions.InvokePrivateMethod[T] (System.Object obj, System.String methodName, System.Object[] pars) (at <5ec6cc0b79ef4c8ca505acc27715c91b>:0)
Ony.OxygenNotIncluded.DGSM2.CharacterContainer_GenerateCharacter.Prefix (CharacterContainer __instance, MinionStartingStats& ___stats, KBatchedAnimController& ___animController, KToggle& ___selectButton, CharacterSelectionController& ___controller, System.Boolean is_starter, System.String guaranteedAptitudeID) (at <5ec6cc0b79ef4c8ca505acc27715c91b>:0)
(wrapper dynamic-method) CharacterContainer.CharacterContainer.GenerateCharacter_Patch1(CharacterContainer,bool,string)
CharacterContainer+<DelayedGeneration>d__47.MoveNext () (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <72b60a3dd8cd4f12a155b761a1af9144>:0)

Build: U52-626616-SC

**Comment by Z2935826653** [comment]
![}0~@JCL23V9)JE{C5G%QU12](https://github.com/user-attachments/assets/3f591955-f5bf-4da5-bc4a-65f9e4749b90)

**Comment by O-n-y** [comment]
Make sure you have the last version of the mod. 
Check out : https://github.com/O-n-y/oxy.mods
**Troubleshooting** section and **How to Report Bugs**

**Comment by O-n-y** [comment]
Closing as no more info provided
