### ISSUE TITLE
[Debug Console] Game Crash

### ISSUE THREAD

**Issue by skystreet8** [O-n-y/oxy.mods#187]
Hi there. After the recent version 644960 update, Debug Console cannot load properly and throws the following exceptions:
`[09:05:51.977] [1] [INFO] Loading mod content Animation [Move This Here:2667816955] (provides DLL, Animation) [DebugConnsole][1]: Patching JobManager.WorkerThread.Run [Exception]: MissingMethodException: Method not found: bool .JobManager.DoNextWorkItem() (wrapper dynamic-method) JobManager+WorkerThread.JobManager+WorkerThread.Run_Patch1(JobManager/WorkerThread) JobManager+WorkerThread.ThreadMain (System.Object data) (at <4e08f3a60ed4421b99a6798f854897c4>:0) System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0) System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0) System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0) System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0) System.Threading.ThreadHelper.ThreadStart (System.Object obj) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0) UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs)`
Then the game will freeze at the Klei logo interface. After deleting the mod information from the mods.json file to force disable the mod, everything will work out fine. The same crash was reported in the Klei forum [here](https://forums.kleientertainment.com/klei-bug-tracker/oni/game-hotfix-644960-crashes-the-game-before-startup-r47235/).

**Comment by MindlessDupe** [comment]
This error is true for the various @ONY mods that I had including Priority Master, Debug Console. Research Master, and a couple others created by @O-n-y. The other thing I noted is that of the various mods I had, ONLY those mods have a subfolder "config" under the folder "mod" in the local storage that seems to be created when activating the mod. Deleting the subfolder allows the game to start, but activating those particular mods again cause a crash and prevent a restart. The Klei patch does not seem to recognized the "config" subfolder. I've notified @O-n-y and Klei on their Bug forum. Thanks for your attention.

**Comment by O-n-y** [comment]
fixed in  1.1.2.85, live on steam

To force update mod:
1) Close the game
2) delete folder /mods/Steam/2041219184
3) start the game, it will re-download the mod

*Due to health issues, the mods work in a pause and will be slow, sorry

**Comment by MindlessDupe** [comment]
Thank you Anya! So sorry you're still ill. Rest and get better, please. The mods can wait.
