### ISSUE TITLE
UI size not resetting upon game restart?

### ISSUE THREAD

**Issue by corrado33** [O-n-y/oxy.mods#2]
I play on 1080p, and I also play at 75% UI scale. If I set the UI scale to 100% before I load the game, then set the UI scale to 75%, the mod is scaled correctly. But if I just leave the scale at 75%, the mod text is too large when I load into the game, and half of the text values are off of the screen. See the picture below.

https://i.postimg.cc/NMLsvyQQ/Oxygen-Not-Included-2019-10-18-22-31-40-527.jpg

I don't know if I'm doing something wrong, and it's not really a huge issue, I just figured you'd want to know!

**Comment by O-n-y** [comment]
Make sure you have the last version of the mod, you can do this using my other mod: Mod Manager

**Comment by corrado33** [comment]
Ah, you are correct. I suppose I should have updated the mod before I mentioned anything. I did look through the comments on the workshop and didn't see anything, but I don't have a discord account so I couldn't look there.

I guess it's my bad habit of not updating things unless something is actually broken. :) You must have fixed this recently, because I don't think I originally downloaded the mod too long ago. 

Anyway, thanks for all the wonderful mods. :)

**Comment by O-n-y** [comment]
Nope, i haven't updated it for a while.
It is just steam workshop have known issue with caching, it can give your outdated mod version. That is one main reason why i made Mod Manager mode, to help solve this issue.
