### ISSUE TITLE
[Incompatible] 'Favorite Buildings - Custom Key Bindings' Mod 1.2.2.3.

### ISSUE THREAD

**Issue by gnoyRi** [O-n-y/oxy.mods#20]
Hi, I've been using your mods happily, and recently I found that I can't change custom key settings in your mod anymore. It constantly crashes whenever I click the 'NONE' button in key settings menu.

I tried this when only your mods are activated (Mod manager, Debug console and Custom key bindings)
Mod manager says Custom Key mod version is 1.2.2.3.

![OxygenNotIncluded 20200715 16;10;48](https://user-images.githubusercontent.com/68320540/87515468-d64dec80-c6b6-11ea-94e9-c097a263c77d.png)
![OxygenNotIncluded 20200715 16;10;59](https://user-images.githubusercontent.com/68320540/87515471-d77f1980-c6b6-11ea-87b3-244109733c4c.png)

Following are what Crash Report says :

Ony.OxygenNotIncluded.ModScreenManager`2+<>c__DisplayClass14_2[T,L].<CreateKeyBindingList>b__2 () (at <2c12b602e9b0465bac81113db918ff10>:0)
KButton.SignalClick (KKeyCode btn) (at <1dcc11867b524f7cb2488468843e982e>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <1dcc11867b524f7cb2488468843e982e>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.EventSystem:Update()

Following are what your Debug Console says :

  [Mod Manager][1]: ModsScreen_BuildDisplay
  [DebugConsole][1]: Error[Exception]: MissingMethodException: void ConfirmDialogScreen.PopupConfirmDialog(string,System.Action,System.Action,string,System.Action,string,string,string,UnityEngine.Sprite,bool)
Ony.OxygenNotIncluded.ModScreenManager`2+<>c__DisplayClass14_2[T,L].<CreateKeyBindingList>b__2 () (at <2c12b602e9b0465bac81113db918ff10>:0)
KButton.SignalClick (KKeyCode btn) (at <1dcc11867b524f7cb2488468843e982e>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <1dcc11867b524f7cb2488468843e982e>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.EventSystem:Update()

  [DebugConsole][1]: Error[Exception]: MissingMethodException: void ConfirmDialogScreen.PopupConfirmDialog(string,System.Action,System.Action,string,System.Action,string,string,string,UnityEngine.Sprite,bool)
Ony.OxygenNotIncluded.ModScreenManager`2+<>c__DisplayClass14_2[T,L].<CreateKeyBindingList>b__2 () (at <2c12b602e9b0465bac81113db918ff10>:0)
KButton.SignalClick (KKeyCode btn) (at <1dcc11867b524f7cb2488468843e982e>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <1dcc11867b524f7cb2488468843e982e>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.EventSystem:Update()

Thank you so much for your effort. Hope for any help that could be provided.

**Comment by O-n-y** [comment]
This mod needs an update to compatibility with API changes introduced in the last game build, I haven't yet updated it.
So will be auto fixed as updated. Thank you for reporting tho!

**Comment by gnoyRi** [comment]
Thx a lot! very happy to know that this is not my 'personal' problem.

**Comment by O-n-y** [comment]
Favorite Buildings updated to 1.2.3.5 release version:
+ Compatibility with game version update AP-420700
