### ISSUE TITLE
It takes a long of time to open MODS in the main menu everytime after installing the mod manager.

### ISSUE THREAD

**Issue by otakutyrant** [O-n-y/oxy.mods#23]
But I have installed only this mod manager.

If I tried to install some mods, the game will crash everytime after Klei Logo.

**Comment by otakutyrant** [comment]
You can check my demostration in [Reddit](https://www.reddit.com/r/Oxygennotincluded/comments/imyalq/it_takes_a_long_of_time_to_open_mods_in_the_main/)

**Comment by otakutyrant** [comment]
My [save_files](https://easyupload.io/nniiol), it will expires in 7 days.

**Comment by O-n-y** [comment]
Tick "Show disabled mods" On - you will see how many exactly mods you have, I can assume it is not mod manager only.
Even tho mods are disabled they are still checked for mod version modification and other information.

if you have too many mods, it could take a time to load those.

**Comment by otakutyrant** [comment]
Suddenly, I cannot even open mods now. I decide to give up this mod manager. Thanks anyway.
