### ISSUE TITLE
Request: Reformat date to YYYY.MM.DD

### ISSUE THREAD

**Issue by kaedys** [O-n-y/oxy.mods#24]
The current date format is DD.MM.YYYY, which is confusing to anyone used to a month-day-year ordering (ie. US, probably others).  Swapping it to MM.DD.YYYY would be just as confusing to everyone else.

YYYY.MM.DD, on the other hand, in unambiguous.  In addition to being easily sortable (probably not super relevant here), it is also difficult to confuse, since YYYY.DD.MM is not a format that's ever really been used.  Most major timestamp formatting standards (ISO 8601, RFC3339, etc) use this ordered due both to its general lack of ambiguity and its easy sortability.

**Comment by O-n-y** [comment]
`Swapping it to MM.DD.YYYY would be just as confusing to everyone else.` this is not true actually, Europe and other parts of the world use DD.MM.YYY notation, which you can check at Wikipedia:
https://en.wikipedia.org/wiki/Date_format_by_country 

YYYY.MM.DD is indeed ISO notation, but it is not as convenient to read, and mostly used in technical documentation.

Currently, I do not plan to change date format, but maybe sometime later I will add such an option to settings.

**Comment by kaedys** [comment]
> Swapping it to MM.DD.YYYY would be just as confusing to everyone else. this is not true actually, Europe and other parts of the world use DD.MM.YYY notation, which you can check at Wikipedia:

That was my point, though.  If you swapped the date format to month-first, those from Europe et al would likely find it as confusing to read as a US person finds day-first to read.  That's why I suggested a format that, while it may not quite be as convenient to read, it at least unambiguous.

However, a date format config option would also work!
