### ISSUE TITLE
Infinite update notification for a few mods

### ISSUE THREAD

**Issue by eleroy5** [O-n-y/oxy.mods#25]
Hi, i have a lot of mods and i use "mods manager".
For a few days, each time i enter the mods menu i receive a notification for updating "Relocate the printing pod" and "Thermal Tooltips"
I have updated them, mod manager indicates the good version and date update.
But each time i enter the mod menu it indicates always that they needs to be updated.
Do you have an idea why updates of those mods are not recognized?

**Comment by O-n-y** [comment]
Please make a screenshot for such mods from Mod Manager Mods list (you can hover "outdated" button to see technical information).
Also, provide at it said in "How to report issue" Mod Manager version you have.

**Comment by O-n-y** [comment]
as there is no more information was provided, closing it for now
