### ISSUE TITLE
[Suggestion/Request] Compatibility between DGSM and Better Neural Vacillator

### ISSUE THREAD

**Issue by MechanosG** [O-n-y/oxy.mods#29]
https://steamcommunity.com/sharedfiles/filedetails/?id=2208943226

The author of BNV says it conflicts with DGSM, I'm guessing because of the extra traits it adds.  Being able to use DGSM and BNV at the same time, would be awesome.

Edit:  I've since tested using both.  They seem to be mostly compatible.  DGSM doesn't show some of the extra traits, and there was some weirdness with Early Bird/Night Owl showing {0} instead of 2, as the point bonus.  In-game the dupes get +2 properly though.  So I'm guessing the only real conflict is the missing traits.  Not being able to select the +8 traits is actually a good thing balance wise in my opinion, but the rest would be nice.

**Comment by O-n-y** [comment]
DGSM not adding anything additional to the game only provides a handful of ability to change existing traits, so if other mod add something extra, it should be the one who adds compatibility.
I am not able to track all other mods changes which potentially could add something extra.

**Comment by MechanosG** [comment]
Err..  let me try to understand/guess from the limited information you gave.  Are you saying that, if DGSM isn't already loading the extra traits, that you'd have to manually add them?  And manually adding them isn't an option, since they'd have to be updated anytime BNV changes?  If that's the case, that's understandable.  But if I ask the dev of BNV about it, the more I understand the situation the better, as he already marked the mod as conflicting instead of making it compatible and likely won't be persuaded easily lol.

**Comment by O-n-y** [comment]
it is loading traits, which the game provides, automatically reading from the game

**Comment by MechanosG** [comment]
Alright.  Thanks.

**Comment by O-n-y** [comment]
it does not add or check anything manually

**Comment by O-n-y** [comment]
But yes, all other mods which add something do it manually and if you want to add compatibility you have to track such and all changes it could have.
if those would add it as base traits added, then those would automatically appear as base traits do.
