### ISSUE TITLE
Favorite Resource Filters

### ISSUE THREAD

**Issue by rainbowdesign** [O-n-y/oxy.mods#3]
It would be nice to either include in Favorite Resource or make a new mod with:

Filter selection menu as in the menu to select what element is filtered by the gas filter only display discovered elements.
Close, resources in the pipe and favorite resources are somehow highlighted and on the top.

A List in the menu of storage compactor or other items that lists the favorite resources.

**Comment by O-n-y** [comment]
Please post ideas in discord #propose-mod-idea, this tracker made for issues only
https://discord.gg/6aNp8zE
