### ISSUE TITLE
Research Manager Crash

### ISSUE THREAD

**Issue by CoreeZz** [O-n-y/oxy.mods#34]
При создании, либо при попытке зайти в действующую игру, крашится игра с включенным Research Manager.
```
(Filename:  Line: -1)
TypeLoadException: Could not resolve type with token 0100002f (from typeref, class/assembly UnityEngine.Input, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
```

**Comment by CoreeZz** [comment]
Если его отключить, всё работает нормально. 

Забыл прикрепить ссылку на мод https://steamcommunity.com/sharedfiles/filedetails/?id=1897096779

**Comment by Tellik** [comment]
Can confirm this as a crashing bug.

(Filename:  Line: -1)

TypeLoadException: Could not resolve type with token 0100002f (from typeref, class/assembly UnityEngine.Input, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)

Verified with only Research Manager enabled. https://gyazo.com/97b1546d8e0f18ca0e3fdbdd7c669d52
Forced latest version using your mod manager to force update for Research Manager. 
Game version: 442712

[04:21:31.206] [1] [INFO] Loading mod content DLL [Research Manager // by @Ony :1897096779] (provides DLL)
[04:21:31.209] [1] [INFO] Loading MOD dll: Release.Mod.ResearchManager.dll
[ResearchManager][1]: Version: 1.0.4.43 initialized

Full crash log: https://pastebin.com/CiLTVMeJ

**Comment by O-n-y** [comment]
Research Manager updated to 1.0.5.46 release version:
+ Compatibility with game version update CS-442154
