### ISSUE TITLE
Schedule Master crash on config

### ISSUE THREAD

**Issue by Callero** [O-n-y/oxy.mods#36]
When clicking the "Shift Created Schedule" in config, the game crashes.
Version 1.1.2.161

Error message details:
`TypeLoadException: Could not resolve type with token 01000078 (from typeref, class/assembly UnityEngine.Input, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)

Ony.OxygenNotIncluded.ModScreenManager`2+<>c__DisplayClass20_0[T,L].<CreateUpDown>b__1 () (at <72ef1481d79a41a0a3116ec53afcdef3>:0)
KButton.SignalClick (KKeyCode btn) (at <823c73e1dded498b9eec52a50d2e15ee>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <823c73e1dded498b9eec52a50d2e15ee>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <86c3eb4a785a41359af7ebb506b04800>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <86c3eb4a785a41359af7ebb506b04800>:0)
UnityEngine.EventSystems.EventSystem:Update()
`

**Comment by O-n-y** [comment]
Updated version: 1.1.3.164  do not have this issue.
