### ISSUE TITLE
Duplicants Generation Settings Manager

### ISSUE THREAD

**Issue by h33im** [O-n-y/oxy.mods#37]
На начальном экране выбора персонажа если выбрать случайного персонажа с двумя характеристиками, например +4 сила +5 уборка, то после корректировки его параметров (например, замена уборки на строительство), обе характеристики становятся по +3. Если выбрать персонажа с 1 характеристикой +10, то после корректировки она станет +7. Точно такая же ситуация уже во время игры.

**Comment by h33im** [comment]
![Screenshot_22](https://user-images.githubusercontent.com/79328785/108538936-6b216400-72f0-11eb-9070-f8ba11370da8.png)
![Screenshot_23](https://user-images.githubusercontent.com/79328785/108538943-6ceb2780-72f0-11eb-8c69-d6e576734b98.png)
![Screenshot_24](https://user-images.githubusercontent.com/79328785/108538946-6d83be00-72f0-11eb-8bb8-ea950af3917f.png)

**Comment by O-n-y** [comment]
_Should be addressed in the upcoming 3.0.9.165_
