### ISSUE TITLE
Duplicants Generation Settings Manager

### ISSUE THREAD

**Issue by CraigCraig** [O-n-y/oxy.mods#38]
Issue with DGSM and the DLC where when you go to select the skill of a dupe, like research, it resets it to level 7.

For example you can randomly generate a dupe and they have +12 in a skill, go to edit them and don't change anything, apply the changes, and their skill goes back to +7.

Version: 3.0.8.116
Save game does not apply as this issue is prior to playing an actual game.

**Comment by O-n-y** [comment]
Please follow https://github.com/O-n-y/oxy.mods how to report the issue properly.

**Comment by O-n-y** [comment]
_Should be addressed in the upcoming 3.0.9.165_
