### ISSUE TITLE
DGSM doesn't read config file at startup

### ISSUE THREAD

**Issue by shulima** [O-n-y/oxy.mods#39]
Since a recent update, DGSM (version 3.0.8.116) appears to have stopped reading or writing its config file. If I enable a setting through Mod Manager, save and restart the game, the setting is reset to disabled.

Debugging steps taken:
- found the config JSON, checked that EnablePrintingPod was enabled, but in game it showed as disabled
- moved away the config, launched the game and enabled the printing pod option, a new file was not generated
- installed the debug console mod, but found no information related to config reading/saving

Additionally, ModManager seems to be suffering from the same problem, as it has stopped persisting the 'mods auto updater' or 'show disabled mods' options.

I'm playing the vanilla game without DLC.

**Comment by O-n-y** [comment]
_Should be addressed in the upcoming 3.0.9.165_
