### ISSUE TITLE
Favorite Buildings ⭐ Custom Key Bindings : Priority keys

### ISSUE THREAD

**Issue by skalou** [O-n-y/oxy.mods#4]
When i try to set a priority in game ( with P key), i can't use the shortcuts keys 1,2,3,...

ONI version LU-372041
Mod Manager v 2.1.0.44
Favorite building v1.2.0.25
some other mods but disabled
i cleared mods cache
tried with a fresh map
french keyboard (AZERTY) but i tested with english settings too (QWERTY)
if i disable Favorite building the priority works with key 1,2,3...

**Comment by O-n-y** [comment]
Fixed in  @1.2.1.2
