### ISSUE TITLE
DGSM Interest Number Reset

### ISSUE THREAD

**Issue by TheExceed** [O-n-y/oxy.mods#40]
Currently in the DLC, Dupes are always at 3 interests, however the number for each interest varies from 1-7.
When editing a dupe at the start of the game, I noticed that it'll change the numbers to +1 even if you did not change the interest.

https://prnt.sc/109jw18
https://prnt.sc/109jw8f

As well as loading a preset crashes the game.

**Comment by O-n-y** [comment]
Interests count can be changed in settings (mod list -> config button).

_Points amount should be addressed in the upcoming 3.0.9.165_
