### ISSUE TITLE
Specific world traits not working post "spaced out" DLC

### ISSUE THREAD

**Issue by Punktr00per** [O-n-y/oxy.mods#41]
Specific World traits in game settings are no longer working. 

i'm trying to create a new world on "Terra" and cannot see the list for specific traits to select, this is also the same when i select other asteroids like "Rime". 

I have checked for mod conflicts as i am using a number of mods however nothing seems to be resolving this issue. random traits are working for "Terra" however the other variants are not.

**Comment by O-n-y** [comment]
WGSM not yet updated for DLC.
