### ISSUE TITLE
DGSM Bug: Not Working For Printing Pod

### ISSUE THREAD

**Issue by dinkocolic** [O-n-y/oxy.mods#43]
**Description of Issue:** 
When the printing pod is ready to create a new duplicant:
1. You are unable to change ALL of the duplicants settings.
2. You are unable to APPLY the changes you do make.

**Steps to reproduce Issue:**
1. Play the game using the Spaced Out DLC (Latest Update as of 3rd Apr 2021).
2. Select the printing pod and press "choose a blueprint"
3. Press the "Duplicant configuration" cog button
4. Be unable to change all the settings.
5. Make sure under mod settings to be using 

- Enable "Enable for printing pod"
- Disable "No Positive Traits"
- Disable "No negative traits"
- Fixed amount of positive traits [3]
- Fixed amount of negative traits [1]
- Fixed interests amount [3]

**Mod version:** v3.0.9.165

Attached is a saved game with the printing pod ready.
[@ ONY.zip](https://github.com/O-n-y/oxy.mods/files/6252144/%40.ONY.zip)

PS: Only two mods were enabled for this issue to occur; DGSM and Mod Manager by ONY.

**Comment by O-n-y** [comment]
Should be fixed in the upcoming 3.0.10.167 build for DLC1
