### ISSUE TITLE
DGSM - I don't know if thats a bug, but...

### ISSUE THREAD

**Issue by Campuu** [O-n-y/oxy.mods#44]
Well, i've downloaded the mod and when i create a new world, the start duplicants are created in that way: http://prntscr.com/11tzsge and i can't configure them properly. When i change anything in the settings in the menu "mods" it gives that error:
"IndexOutOfRangeException: Index was outside the bounds of the array.

Ony.OxygenNotIncluded.DGSM.CharacterContainer_GenerateCharacter.Postfix (CharacterContainer __instance, CharacterSelectionController ___controller, System.Boolean is_starter, System.String guaranteedAptitudeID) (at <91027da7a0dd4bf893c8785b2db44b73>:0)
(wrapper dynamic-method) CharacterContainer.GenerateCharacter_Patch1(object,bool,string)
CharacterContainer+<DelayedGeneration>d__45.MoveNext () (at <f834fb9792e545c0aa06cca79073875a>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <b8388ffefd6046f8a7b4080349da72eb>:0)"

My mod version is: 3.0.9.168
Can you help me?

**Comment by O-n-y** [comment]
you have an outdated version 
actual one: 3.0.10.167

**Comment by liushilive** [comment]
There is a network problem in China. It cannot be updated. Can you provide local download?

<liushilive@outlook.com>

**Comment by O-n-y** [comment]
this is impossible sorry, all my mobs only available in steam.
i recommend to read Troubleshooting on the mod page.
