### ISSUE TITLE
Ony's Favourite Resourses Mod 

### ISSUE THREAD

**Issue by ripu31082003** [O-n-y/oxy.mods#47]
So hey I have download your Favourite Resourses Mod  but I can't use it in my current v420800 Automation Pack... I don't know why, I mean in the mod setting I still can enable it, but when join in a game (everything is normal) but your mod doesn't work out (no plus (+) symbol beside the current resourses like usually, how could I fix this?

**Comment by O-n-y** [comment]
please read https://github.com/O-n-y/oxy.mods for how to report issue properly

**Comment by O-n-y** [comment]
A there is no more information was given, I am closing this one for now.
Once the information provided, it could be re-opened.
