### ISSUE TITLE
ONI Update to Harmony 2.0

### ISSUE THREAD

**Issue by xialeth** [O-n-y/oxy.mods#48]
With the recent Spaced Out! Merge Update (currently only launched for Spaced Out! owners), the game has updated to Harmony 2.0 and thus all old DLCs have become obsolete: https://forums.kleientertainment.com/forums/topic/130712-oni-is-upgrading-to-harmony-20/

Is it possible to get the ONI mods updated, too? 
I personally really love the Duplicant Trait Selector, but I would assume that all ONI mods will suffer once the update rolls out to the base game, too.

**Comment by O-n-y** [comment]
I will be updating my mods, yes
You can get more info in Discord

**Comment by 0xErnie** [comment]
I think this issue should be kept open to track the process and closed when the changes have been done.
