### ISSUE TITLE
Debug Console - ONI is denied access to DLL file

### ISSUE THREAD

**Issue by TroublesomeCorvid** [O-n-y/oxy.mods#49]
I've disabled all other mods and deleted the mods.json file.  When it's the only mod active, ONI has no idea what to make of it, throwing up the "Help! A black hole at my game!" default message for the game devs.  Looking through the player.log file, it looks like the game is being denied access to the file by my system...

...However, this still somehow persists even if I delete the mod's folder (on my system, at D:/Media/Documents/Klei/OxygenNotIncluded/mods/Steam/2041219184).  Which means that for some reason, something is causing my system to protect this one folder alone from being accessed by ONI.  And I honestly have no idea why or how.

(Just so you know, I'm not running anything special for antivirus/antimalware software - just the basic stuff Windows uses by default.)

Attached is the player.log file.  Any assistance would be greatly appreciated.

[Player.log.txt](https://github.com/O-n-y/oxy.mods/files/6722177/Player.log.txt)

**Comment by O-n-y** [comment]
Try removing the whole folder /mods and start the game again.  
This caused not by the contents of the file, but the system you are running, this means for some reason file/folder have not correct access rights.

**Comment by O-n-y** [comment]
A there is no more information was given, I am closing this one for now.
Once the information provided, it could be re-opened.
