### ISSUE TITLE
DGSM Newest version (v3.0.14.198) is broken 

### ISSUE THREAD

**Issue by jhammersholt** [O-n-y/oxy.mods#51]
Playing vanilla and haven't bought DLC

**Comment by O-n-y** [comment]
There is not enough information provided, provide more information, i will re-open issue
https://github.com/O-n-y/oxy.mods/blob/master/README.md

**Comment by jhammersholt** [comment]
Not sure how i find the crash info you need, but just letting you know its broken

check the steam workshop page where a lot of users reports the same problem
https://steamcommunity.com/workshop/filedetails/discussion/1838445101/3044979493842676616/

**Comment by O-n-y** [comment]
DGSM updated to 3.0.15.200 release version and available on Steam!
ChangeLog:
+ Backwards Vanilla compatibility (Harmony 1 support, while they not updated it to Harmony 2)
