### ISSUE TITLE
Mods outdated

### ISSUE THREAD

**Issue by Jemsterr** [O-n-y/oxy.mods#52]
Smart Mop 
No Drop
Research Manager
(possibly others I don't have subscribed)

Are listed as "outdated" in Mod Manager.  Probably need to update to Harmony 2?

I assume you know about it, but there didn't seem to be a ticket for this, so putting this here.

**Comment by O-n-y** [comment]
you can get all information in discord
https://discord.gg/hyZD84Xp

all mods once updated, will be released on steam.
