### ISSUE TITLE
@DGSM Click Error

### ISSUE THREAD

**Issue by BlackHorde22** [O-n-y/oxy.mods#53]
Action: Click on a trait changer after a few times I got this error.
Repeatable: Yes.

![Screenshot 2021-08-13 235407](https://user-images.githubusercontent.com/13217780/129367810-4f3973d1-c562-41bc-89a8-da5cfffd3fc5.jpg)
![Screenshot 2021-08-13 234516](https://user-images.githubusercontent.com/13217780/129367811-c3af207a-acad-4a29-8912-c6f0da7ae7ef.jpg)

**Comment by BlackHorde22** [comment]
would you like to to share screen and do it again?

**Comment by O-n-y** [comment]
No need, thank you.
I will check and try to reproduce.

**Comment by O-n-y** [comment]
Will be fixed on the upcoming release. 3.0.16.205+

**Comment by O-n-y** [comment]
3.2.21.265
