### ISSUE TITLE
DGSM not working with new update

### ISSUE THREAD

**Issue by MacTheBlack** [O-n-y/oxy.mods#56]
Maybe the mod is not working with the new trait "Ancient Knowledge"

[dgsm.txt](https://github.com/O-n-y/oxy.mods/files/7306001/dgsm.txt)

**Comment by O-n-y** [comment]
Will be fixed on the upcoming release. 3.0.16.205+

**Comment by O-n-y** [comment]
fixed on 3.2.21.265
