### ISSUE TITLE
Problem with duplican's reroll buttons

### ISSUE THREAD

**Issue by Gohu0** [O-n-y/oxy.mods#59]
When I want to choose a blueprint and I open the printpod the first time I have all the reroll buttons but if I close the window and open it again the buttons disappear. I don't know if it's normal, in doubt I prefer to report it.

Step to reproduce:
1) Open the window to choose a blueprint
2) Close the window
3) Open it again
build: .265
![image](https://user-images.githubusercontent.com/65341034/138564346-75ff7873-6ebd-49c0-ba33-49edd8253e71.png)

**Comment by O-n-y** [comment]
Should be fixed on upcoming  mod update (3.2.23.270+ version)
