### ISSUE TITLE
Research Manager queue order changes when loading a save game

### ISSUE THREAD

**Issue by dawnmist** [O-n-y/oxy.mods#6]
OS: Debian Linux 10 (buster), 64bit
Research Manager Version: 1.0.1.2

Research Manager's queued research is reordered when opening a save game. I'd been researching Advanced Research when I'd saved:
![image](https://user-images.githubusercontent.com/5810277/68066441-26388d80-fd8c-11e9-9ac8-b22e6351d7d8.png)

That one point in Distillation is from one of the Schedule Master testing reloads (for #5 ) last night. I fixed the research order then, and it's scrambled the order again when loading today.

**Comment by O-n-y** [comment]
This issue should be fixed in actual version 1.0.2.20+
