### ISSUE TITLE
Favorite Buildings shortcuts conflict when setting numbers for automated circuits

### ISSUE THREAD

**Issue by waingt** [O-n-y/oxy.mods#60]
When selecting automated circuits (sensors, gates, etc.), the Favorite Buildings shortcut keys (e.g., 1,2,3) are still in effect, preventing me from setting numbers.

Favorite Buildings v1.2.5.8
ONI version U36-481873-S with DLC Spaced Out!

**Comment by O-n-y** [comment]
Could you please make an example for how to replicate?
