### ISSUE TITLE
[No Drop] things stuck in the wall

### ISSUE THREAD

**Issue by GongT** [O-n-y/oxy.mods#61]
Reload the game will move them out.

Mod Version: 1.2.2.25    
No other mods enabled

![image](https://user-images.githubusercontent.com/2265048/140601276-7bf9b3f7-3c06-494c-8210-57fa8090abcb.png)
[Uploading 金色的卫城.zip…]()

**Comment by O-n-y** [comment]
please upload game save where this can be reproduced

**Comment by GongT** [comment]
[金色的卫城.zip](https://github.com/O-n-y/oxy.mods/files/7490461/default.zip)

**Comment by GongT** [comment]
When duplicants on a ladder:
* cancel his job
* turn on an alert
* time to sleep

**Comment by O-n-y** [comment]
thank you, i will check this out!

**Comment by hrottipharmd** [comment]
Appearing to be having same issue.  Noticed it seems to happen around ladders/fire poles and airflow tiles.  Also appears to be dropping into natural tiles as that tile was put in via sandbox with nothing behind it.

Mod Version: 1.2.2.25
No other mods enabled

![image](https://user-images.githubusercontent.com/38888732/165832409-c25d1785-9bdb-4c1b-8581-725ae25117c5.png)
![image](https://user-images.githubusercontent.com/38888732/165832534-43aaa1e3-b73f-4aed-8a3d-04ca1dfb4c61.png)


[Test for bugs.zip](https://github.com/O-n-y/oxy.mods/files/8585813/Test.for.bugs.zip)

**Comment by O-n-y** [comment]
fixed on release build 1.2.4.27
