### ISSUE TITLE
[BUG]can't activate this 'Mod Manager' Mod

### ISSUE THREAD

**Issue by tangbenDY** [O-n-y/oxy.mods#66]
game version: U39-490405-S
mod version:v2.12.4.87

I deleted all mods and re-installed my game,but even if I sub only this mod, it showed in red  and the game crush.

and I don't know how to upload image here..
please help me ! 
I can't go  on my game without the mod!

**Comment by O-n-y** [comment]
This is an outdated version. Actual version number: 3.2.23.271

**Comment by tangbenDY** [comment]
> 
it is still 2.12.4.87in steam workshop..

**Comment by O-n-y** [comment]
then you have issue with steam cache, this is not a mod issue.

**Comment by tangbenDY** [comment]
> then you have issue with steam cache, this is not a mod issue.

I reinstalled my steam and it is still like this..

**Comment by tangbenDY** [comment]
> then you have issue with steam cache, this is not a mod issue.

when is the last version?
 it shows 2121.7.21 my here
