### ISSUE TITLE
Mod out-of-date on vanilla

### ISSUE THREAD

**Issue by nemesis-1** [O-n-y/oxy.mods#67]
Cannot enable the mod on vanilla.

OS: Windows
Game Version: "BUILD: U39-490405-V" (vanilla)
Mod Version: 3.0.9.168
  note: version got by file details, file name is `Release_DLC1.Mod.DGSM.dll`
  your mod manager shows version as unknown

How to reproduce:
1. Unsubscribe to all mods on steam
2. Rename the folder `Documents\Klei\OxygenNotIncluded`, game will create a new one with clean data.
3. Subscribe to DGSM
4. Run the game, open the mod menu, mod is listed as out-of-date and can't be enabled. Config button is also not present.

**Comment by O-n-y** [comment]
you have an outdated version.
actual version number **3.2.23.271**
https://steamcommunity.com/sharedfiles/filedetails/changelog/1838445101

this is steam issue cache, not the mod
