### ISSUE TITLE
Feature Request: No Drop

### ISSUE THREAD

**Issue by Tellik** [O-n-y/oxy.mods#7]
Would it be possible to have a config option for this mod where if someone drops something that it's auto flagged for sweeping?

**Comment by O-n-y** [comment]
Can you be more descriptive about what exactly do you mean?

**Comment by Tellik** [comment]
"This mod will prevent Duplicants from dropping resources they carry when they on ladder (for example when they want to catch their breath which do interrupt current task and cause drop of all carried resources), instead they will hold those till better place to drop."

When they choose a better place to drop, it stops using that resource for it's original purpose. Which kind of scatters and stacks them in weird places. 

I would just like an option, where if a dupe drops something via this mod, that it auto flags it for sweeping.

**Comment by O-n-y** [comment]
should be in upcoming 1.1.0.15 version
