### ISSUE TITLE
Only get care package option even after raising dupe number

### ISSUE THREAD

**Issue by Bunyan1** [O-n-y/oxy.mods#70]
Hello!  I've loved the mod and worked fine initially.  I set the "Print only care packages when have alive dupe count" to 12. Played with 12 dupes for quite a while (1,000 cycles or so) and wanted to change it to 20 to get more dupes. Changed the amount and saved, but the portal will still only give care packages.  This happens regardless of how many mods I have running.  I've used your mod manager to manually update the mod, but no affect.

Is that initial number not able to change? Or if it is, how do I change it and make it take affect in the game? Thanks!

Playing on Windows; Vanilla game build U39-490405-VD
Mod version: 3.2.23.271
[Mod Trial.zip](https://github.com/O-n-y/oxy.mods/files/7931789/Mod.Trial.zip)

Edit: If I turn the mod off, it reverts to normal.  If I turn the mod back on, it goes back to only giving care packages.  I've uninstalled the mod and then reinstalled the mod with the same affect.  Basically if the mod is on, no matter what I set the dupe/care package setting to, I only get care packages.  It just seems that although the setting is being saved in the mod config, it's not impacting the game correctly.

**Comment by Bunyan1** [comment]
Update: I've changed the setting for the number of dupes a number of times, usually from 12 to 20 or something inbetween.  Just for kicks and trying to get the mod to work again, I fiddled with jumping it up to 150.  Well, low and behold, it seems to be behaving normally again.

Also, just for troubleshooting reference, if I uninstalled the mod, played for a bit, resaved, then re-installed the mod, it would always come back with the number of dupes already set at the previous amount, even if I deleted the mod folder.  But then it would again revert to only offering care packages even when the number of dupes wasn't up to that number.  Strange.

**Comment by O-n-y** [comment]
`Also, just for troubleshooting reference, if I uninstalled the mod, played for a bit, resaved, then re-installed the mod, it would always come back with the number of dupes already set at the previous amount, even if I deleted the mod folder. But then it would again revert to only offering care packages even when the number of dupes wasn't up to that number. Strange.`
nothing strange, config located in another folder mods/config/

**Comment by O-n-y** [comment]
Can you also screenshot your settings of DGSM config please? As i was not able reproduce this issue on my own

**Comment by Amiplaize** [comment]
I am having the same problem. 
Game version: U40-494396-V
I own the base game and Spaced Out, but Spaced Out is deactivated. 
World seed: OCAN-A-945295274-0
Mods: DGSM (no others)

I have the maximum dupes set to 20. 
I have 10 dupes in my colony. 
I am only able to choose items. No more dupes are showing up in the printing pod. 

Here is a screenshot of the config file for this mod. 
![image](https://user-images.githubusercontent.com/88278451/154872636-90a915ab-bb7f-4528-b3cd-dc37422eea80.png)

Here is my save file.
[Laboratory.zip](https://github.com/O-n-y/oxy.mods/files/8105340/Laboratory.zip)

**Comment by Amiplaize** [comment]
After some testing: 

The max number of dupes is 20. I can get up to 10 dupes before it only offers items.
I increased the max number of dupes to 21. I can get up to 11 dupes before it only offers items.
I increased the max number of dupes to 22. I can still only get 11 dupes. 
I increased the max number of dupes to 23. I can now get 12 dupes. 

It seems to be following a formula: ActualMaxDupes = CEILING(MaxDupes/2)

**Comment by O-n-y** [comment]
Do you have same issue with DLC activated or only on Vanilla?

**Comment by Amiplaize** [comment]
I only did one test with the DLC (first time I've ever run the game with DLC activated so I don't know if one test is representative), but it seemed to be fine. I set max dupes to 10 and I got 10 dupes before the printing pod stopped offering them.

**Comment by O-n-y** [comment]
currently i am not able not reproduce this issue with Vanilla or DLC, there should be something else which affect this, as only few people have this issue.

as far as i know, here is no such formulla ` ActualMaxDupes = CEILING(MaxDupes/2)`

i will re-open it if i find how to reproduce it or there will be new information provided

**Comment by O-n-y** [comment]
> I only did one test with the DLC (first time I've ever run the game with DLC activated so I don't know if one test is representative), but it seemed to be fine. I set max dupes to 10 and I got 10 dupes before the printing pod stopped offering them. It's only in Vanilla game for me.

please write me PM in discord
