### ISSUE TITLE
Crash the game when push shortcut keys

### ISSUE THREAD

**Issue by bigwheel** [O-n-y/oxy.mods#72]
- OS: Windows 11 21H2 22000.469
- game version: U40-494396-V
- Favorite Buildings Custom Key Buildings: v1.2.5.8
- mods enabled: so many (20+)

# Error situation

Play the game few hours and use shortcut keys. Firstly the keys work well but suddenly error occurs.

Debug console shows error message like `NullReferenceException`.

<img width="1920" alt="スクリーンショット 2022-02-05 212545-1" src="https://user-images.githubusercontent.com/826646/152644009-af619ab9-c54a-4ac7-98f5-9553be9cd1fb.png">
<img width="1012" alt="スクリーンショット 2022-02-05 212545-2" src="https://user-images.githubusercontent.com/826646/152644011-7aa4397e-1f22-453e-93c4-513c9cc522a0.png">

**Comment by O-n-y** [comment]
`mods enabled: so many (20+)`
try without other mods and let me know if this issue still can be replicable  (you can leave other of my mods On if you have any, as i am certain those can't provide any issue)

**Comment by O-n-y** [comment]
is there is still issue with other mods disabled?

**Comment by bigwheel** [comment]
Could you give me 1 more week in real time ?
I try without any mods 3 days in game time but it haven't happen.
It happens 4 or 5 days in game time then I need to test more few days.

**Comment by O-n-y** [comment]
no problem, just update the ticket once you get it :)

**Comment by O-n-y** [comment]
i am thinking some other mod could cause this

**Comment by bigwheel** [comment]
<img width="1920" alt="スクリーンショット 2022-02-11 11 16 07" src="https://user-images.githubusercontent.com/826646/153528118-971f8e3f-c194-4da2-a46a-e1a1f9b669ba.png">

Mod was almost only Favorite Buildings Custom Key Buildings but crashed.
However, I am now doubting my keyboard. It is special keyboard with some macro by https://github.com/qmk/qmk_firmware
It taps two keys quickly (< 20ms).

I'm trying with plain keyboard. It will make it clear if the keyboard is the cause.

**Comment by bigwheel** [comment]
<img width="1920" alt="スクリーンショット 2022-02-11 22 42 16" src="https://user-images.githubusercontent.com/826646/153602090-b9ca5f5c-ea28-453d-86ef-edd774048caa.png">

The error happened with logicool bluetooth keyboard.
Also, I deleted `C:\Users\kbigwheel\Documents\Klei\OxygenNotIncluded` therefore I guess this is not configuration problem.

Finally I could think of no other cause than the "Favorite Buildings Custom Key Buildings" mod itself.

P.S.
Anyway, thank you for your gread mods ! Especially I cannot play oni without this shortcut key mod <3
I sent 1000RUB through paypal. If you get pleasure from it, I'm happy too.

**Comment by O-n-y** [comment]
please write me in discord PM

**Comment by bigwheel** [comment]
Mod version: debug message enable version 1.2.6.12

Sorry for the late reply.
New output is here:

<img width="1920" alt="スクリーンショット 2022-02-19 17 23 14" src="https://user-images.githubusercontent.com/826646/154793196-d42325e2-d394-4ccc-8b25-ee8f83732c37.png">
<img width="1920" alt="スクリーンショット 2022-02-19 17 23 18" src="https://user-images.githubusercontent.com/826646/154793195-c65437b9-68a4-4512-8c8b-75a9b27d173f.png">
<img width="1920" alt="スクリーンショット 2022-02-19 17 23 21" src="https://user-images.githubusercontent.com/826646/154793193-0982fbaa-2d7a-4b6a-a659-10f115e553b0.png">

The full of log is this: https://gist.github.com/bigwheel/d1d1f475c72d11c671abbbfde4ef7f9b

**Comment by O-n-y** [comment]
Thank you, will be fixed on next release build, for now you can play on the one you have (it should now cause any issue for you any more)

**Comment by bigwheel** [comment]
@O-n-y Thank you for the kind thoughts !
