### ISSUE TITLE
[DGSM] Turning on this mod will disable the translation of the game settings interface under the planet to create a new game selection

### ISSUE THREAD

**Issue by jilinge2** [O-n-y/oxy.mods#73]
OS: Windows 10 21H1 19043.1466
game version: U40-494396-S
DGSM - Duplicants Generation Settings Manager: v3.2.23.271
mods enabled: only this Mod 
Turning on this mod will disable the translation of the game settings interface under the planet to create a new game selection

**Comment by O-n-y** [comment]
do you still have this iss on  3.7.0.167?
