### ISSUE TITLE
(Mod Manager)Feature Request: Overlay-web browser and steam-links

### ISSUE THREAD

**Issue by rogermartensson** [O-n-y/oxy.mods#74]
Great work on the Mod.

I noticed that you open up the browser on many links.

Would you consider adding support for the ingame overlay browser and perhaps steamlinks?
This should probably be an option for the user to choose in which way to use for accessing links. (Maybe regular links should be default, as it is using now)

Quick search gave this link. Information about steam://-links can easily be found too in the documentation.
https://partner.steamgames.com/doc/api/ISteamFriends#ActivateGameOverlayToWebPage

**Comment by O-n-y** [comment]
why this would be needed? currently, i do not see the reason, the only information is used currently from steam - information about mods author to be shown.

**Comment by O-n-y** [comment]
as there is no more additional information provided, closing this one for now
