### ISSUE TITLE
(Mod Manager)Feature request: Mod Compability Report

### ISSUE THREAD

**Issue by rogermartensson** [O-n-y/oxy.mods#75]
Sometimes there are concerns about Mods and or out-dated mods with working replacements.
This mod could be a good place to have a feature to give information about Mods regarding these issues.

Keeping a good list of information about Mods could be a daunting task but this could be a Community Effort to "crowd source" information and store this information into a compatibility "database". Eg. Mod XYZ is outdated/removed, but Mod XYZ Revisited is a replacement/drop-in replacement.

**Comment by O-n-y** [comment]
How exactly do you propose to get this information?

**Comment by O-n-y** [comment]
as there is no more additional information provided, closing this one for now
