### ISSUE TITLE
my game has been crashing on launch since the update 

### ISSUE THREAD

**Issue by Killertale-123** [O-n-y/oxy.mods#77]
![Screenshot 2022-02-26 224816](https://user-images.githubusercontent.com/100499208/155867383-f1bad438-3028-49ad-8a61-951986ed8f41.png)

**Comment by O-n-y** [comment]
yes, this is known issue, it will require an update

**Comment by Killertale-123** [comment]
do i need to update it

**Comment by O-n-y** [comment]
when the release version will be out (not yet), more information you can get on my discord.

**Comment by O-n-y** [comment]
updated to 2.13.6.104
