### ISSUE TITLE
Duplicants Generation Settings Manager changing printing delay to 2.5 cycle

### ISSUE THREAD

**Issue by nessumo** [O-n-y/oxy.mods#8]
Version: 2.2.0.0
OS: OSX
Enabled mods: DGSM

Steps to reproduce:
* Install DGSM with default settings
* wait for first duplicant print in cycle 3
* print duplicant

Expected:
* next duplicant will be printed in 3 cycles

Observed:
* next duplicant will be printed in 2.5 cycle

[save.zip](https://github.com/O-n-y/oxy.mods/files/3852757/save.zip)

**Comment by O-n-y** [comment]
was fixed in 3.X versions
