### ISSUE TITLE
[DGSM] Enabling DGSM breaks the Printing Pod Duplicant generation

### ISSUE THREAD

**Issue by Exe008** [O-n-y/oxy.mods#80]
**OS:**
Windows 10

**Game version:**
Spaced-out U41-498381-5D

**Full description of issue:**
When the printing pod activates, the Dupes should generate with certain interest-bonuses based on their positive and negative traits. 
With DGSM enabled, even if a dupe spawns with 3 negative traits, a maximum of 1 negative bonus will be added to the skill. (E.g.: An "anemic + narcoleptic + mouth breather" dupe should get a bonus of +15 to their skill for a total of 7+15, but with DGSM enabled only a single total bonus of +5 would is added. Or sometimes no bonus at all!)
Since the dupe selection on game start only allows for 1 positive and 1 negative trait, I do not know if the bug also applies there.

**The way to reproduce it:**
Get the printing pod to activate after 3 cycles in the game, add up the trait bonuses for the dupes and compare to what they should have. Especially look for dupes with multiple negative traits. Notice how for single interest dupes (7 base) the total skill level will never be above 7 base +5 bonus = 12 total, despite up to +15 should be added for a total of 22. (according to https://oxygennotincluded.fandom.com/wiki/Duplicant#Negative_traits )

**Provide mod version:**
Steam subscription, v.3.2.23.271
Only other mod running was ONI Mod Manager, I also tried with even that one disabled.
The settings for DGSM do not matter, it happens with any settings. I used only 3 negative traits for the screenshot for demonstration purposes.

**Image:**
![image](https://user-images.githubusercontent.com/102608643/160654384-7ebd1657-aa24-492d-ad29-004d271f21b1.png)

**Save File:**
[The Ultra Cosmos.zip](https://github.com/O-n-y/oxy.mods/files/8373044/The.Ultra.Cosmos.zip)

**Comment by Exe008** [comment]
Looking at DGSM with default settings (only the "enable for printing pod" and "enable printing pod reroll" options are enabled, every other option unused), I noticed something else that could be related:

When rerolling the printing pod dupes, every dupe only ever comes with 1 positive and 1 negative trait, never more and never less. With DGSM completely disabled, dupes show up with 1-3 positive and 1-3 negative traits as usual. (I feel like this might be another unintended effect of DGSM.)
So... maybe when in DGSM the option "3 fixed negative traits" is enabled, the dupe shows up with 3 negative traits, but only 1 negative trait is used for determining their skill level.

E.g.: In my provided screen shot, the second dupe arrives with a bonus of +0. Maybe they arrive with 1 negative trait which does not provide any bonus to the skill (Gastrophobia, Pacifist, Squeamish or Yokel) and then DGSM overrides the 1 trait with 3 new negative traits. But the calculation for the skill bonus was done only with the 1 original trait and not done again for the 3 new traits.

**Comment by Exe008** [comment]
Dupes who spawn with 2 or 3 interests which include both of the strength based skills (Tidying and Supplying) are broken in the vanilla game, just in case you will run across one of those while debugging. I created a bug report for that on the Klei forums already.

![Vanilla Skill Bonus broken 3](https://user-images.githubusercontent.com/102608643/160807745-b74cb7d7-6d61-4641-9dba-bee30e694ee7.png)
![Vanilla Skill Bonus broken 2](https://user-images.githubusercontent.com/102608643/160807752-04944f07-eed9-4065-baf6-49b8da4aed8c.png)

**Comment by Exe008** [comment]
Turns out, the bug in the base game is not a bug. The game runs correctly, the displayed values (for 2+ interest dupes with both Tidying and Supplying) are initially confusing but correct.
Either way, this still leaves the original issue with DGSM. :/

**Comment by O-n-y** [comment]
changes made in last release build

**Comment by Exe008** [comment]
Awesome, thank you!
