### ISSUE TITLE
[Mod Manager] Crash on attempting to update mods, caused by missing sanity check

### ISSUE THREAD

**Issue by Vectrobe** [O-n-y/oxy.mods#81]
A not-null and not-empty check on the URL string is necessary, else the update-mods-on-startup feature just crashes the game if any mods exist that dont have an obtainable URL.

> ArgumentNullException: Value cannot be null.
> Parameter name: requestUriString
> 
> System.Net.WebRequest.Create (System.String requestUriString) (at <aa976c2104104b7ca9e1785715722c9d>:0)
> Ony.OxygenNotIncluded.ModManager.FileDetailsDownloader.Download (System.String url, System.String filePath) (at <e110115b507542ff85f0c5ef350259fe>:0)
> Ony.OxygenNotIncluded.ModManager.Updater+<Update>d__16.MoveNext () (at <e110115b507542ff85f0c5ef350259fe>:0)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <9fe2cbebfa394c8da6af069ec8cc9ef4>:0)
> 
> Build: U41-498381-S

**Comment by O-n-y** [comment]
Provide the mod name or url which cause this issue

**Comment by O-n-y** [comment]
should be resolved at current release version of the mod 2.13.7.125
