### ISSUE TITLE
[Duplicant Generation Settings Manager] crash when try to edit starting dups

### ISSUE THREAD

**Issue by Wolfking239** [O-n-y/oxy.mods#84]
Game Version: U42-509629-5
Issue: When trying to start a new game and tried to edit starting duplicants game crashes. With or without any other mods (even mod manager and debug).
Mod version:  3.2.23.271
![image_2022-06-06_200857912](https://user-images.githubusercontent.com/4014207/172149733-fadfcb57-bdab-4f23-83f6-c637c7e9c5ac.png)
![image_2022-06-06_201216677](https://user-images.githubusercontent.com/4014207/172150175-9eebda0b-dc1b-4bd3-9d1f-f4ed3a86e83b.png)

**Comment by O-n-y** [comment]
this is an outdated version
