### ISSUE TITLE
[DGSM] Why crashed?

### ISSUE THREAD

**Issue by vmann777** [O-n-y/oxy.mods#85]
https://youtu.be/mgwm7KwA0Jw
(I'm sorry that I uploaded it on YouTube link because of the capacity of the video.)

more info:
TypeLoadException: Could not resolve type with token 01000060 (from typeref, class/assembly PanelColors, )

Ony.OxygenNotIncluded.DGSM.EditableTitleBar_OnSpawn+<>c__DisplayClass0_0.<Postfix>b__0 () (at <aeda084405d543e2af31e7a8b1b52fa5>:0)
KButton.SignalClick (KKeyCode btn) (at <3366109ff608488f8317d0b43357f1ba>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <3366109ff608488f8317d0b43357f1ba>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <0b23117e1c7442f8b1842fe2f3bf6fcb>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <0b23117e1c7442f8b1842fe2f3bf6fcb>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U42-509629-V

mod version: 3.2.23.271
play: vanilla

**Comment by O-n-y** [comment]
please use last version which is: 3.3.27.294
