### ISSUE TITLE
"No Drop" crashing frequently

### ISSUE THREAD

**Issue by kfishkin** [O-n-y/oxy.mods#87]
since the 'fast friends' update, 'No Drop' has started crashing frequently, here's the appropriate part of the log:

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.RemoveAt (System.Int32 index) (at <c56f162e674a4c7185e7d411a3ee1695>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () (at <c56f162e674a4c7185e7d411a3ee1695>:0)

Build: U42-510972-S

**Comment by O-n-y** [comment]
THis issue should be resolved in current release version of the mod 1.2.4.27
