### ISSUE TITLE
Mod - WGSM - World Generation Settings Manager 

### ISSUE THREAD

**Issue by emmigeek** [O-n-y/oxy.mods#9]
So, I started having trouble with the WGSM after the latest ONI update.
I checked out your instructions over at steam workshop page.  I went through, using the mod manager (love that mod by the way) and updated EVERYTHING (I actually clicked update everything a couple times just to make sure everything was up to date. 
I turned off ALL mods BUT the mod manager and the WGSM just to make sure it WAS the WGSM that was the problem. 

Then I went in to start a new game. 

On choosing the world settings, clicking the arrows to change settings don't do anything. 
if I back out, then go back into settings it shows as what I'd clicked before, however clicking the arrows still didn't do anything until I backed out, then reopen settings and it'll show them as changed based on how many times I clicked the arrows before backing out. I gave up trying to tweak those settings and decided to just try to play the game.

it seems to start the new game fine at first, then it just sits there on the loading screen, doesn't bring up the new dupes to start the game itself. I had to close the game out completely and reopen it. 

On checking the mods, the WGSM is light red and unclicked. Since there is no save game file I took screenshot clips and numbered them in the order I did things. 

I haven't had trouble with your mods before. I love the work you do. I hope this is clear on what I'm experiencing. 

![mods loaded_1](https://user-images.githubusercontent.com/57694302/71084234-d4dd3580-2162-11ea-8c7d-3d23c0d8b568.PNG)
![arrows dontwork_2](https://user-images.githubusercontent.com/57694302/71084259-e45c7e80-2162-11ea-971b-7a13195237d6.PNG)
![backout_3](https://user-images.githubusercontent.com/57694302/71084265-e7f00580-2162-11ea-9cf6-3b92423a1144.PNG)
![back in_4](https://user-images.githubusercontent.com/57694302/71084275-ec1c2300-2162-11ea-97fd-8b9d42f4a349.PNG)
![load stuck_5](https://user-images.githubusercontent.com/57694302/71084284-efafaa00-2162-11ea-88df-898ec8753329.PNG)
![restarting_6](https://user-images.githubusercontent.com/57694302/71084291-f3433100-2162-11ea-90b5-938f00676725.PNG)

**Comment by O-n-y** [comment]
You have outdated version, last version is:
Version: 2.0.2.4
(https://steamcommunity.com/sharedfiles/filedetails/changelog/1833427385)

**Comment by emmigeek** [comment]
huh. Ok, doing that now. I wonder why it didn't update.
