### ISSUE TITLE
[Research Manager] ordering issue on Ubuntu

### ISSUE THREAD

**Issue by BeardMan42** [O-n-y/oxy.mods#90]
OS:
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"

Game Build: U42-514976-5

Mod Version: v1.1.8.175

Description:
As described in #6 and #46, presets seem to load in tree order based on highest tier, regardless of original order added.

This is easy to reproduce on my system:
1. Start a new world (survival/spaced out/any dupes) with only Research Manager enabled (cleared cache and only enabled Research Manager).
2. Dig far enough to get 400kg of copper.
3. Build research station
4. Open Research tab
5. Select, in this order: Basic Farming, Power Regulation, Meal Preparation, and Internal Combustion. 
![image](https://user-images.githubusercontent.com/29062879/180665215-8992a3d2-79a6-4a5e-9174-8002eb759b9b.png)
6. Save as Preset
7. (optional) Clear Queue
8. Load Preset
9. Items are now ordered as follows: Basic Farming, Meal Preparation, Power Regulation, and Internal Combustion. 
![image](https://user-images.githubusercontent.com/29062879/180665202-961f9f2d-5d46-4aa9-ae1b-3e5e3d8cca32.png)
10. Saving the game and reentering does the same thing.
config.json reads as follows (abridged):
  ```
"ConsoleEnabled": false,
  "ShowConfig": true,
  "AutoLoadPreset": true,
  "DisableResearchCompleteNotification": false,
  "ResearchQueue": [
    "FarmingTech",
    "PowerRegulation",
    "FineDining",
    "Combustion"
  ],
```
[files.zip](https://github.com/O-n-y/oxy.mods/files/9176695/files.zip)

I think that covers everything. let me know if you need anything else

EDIT: Typo

**Comment by O-n-y** [comment]
Should be fixed on next release build (should be on BETA today or tomorrow)
Join discord to track progress: https://discord.gg/By2C6RC

**Comment by O-n-y** [comment]
Research Manager 1.3.1.6 release version is live on Steam
