### ISSUE TITLE
Mod Manager uninstalls all Mods when starting in offline mode

### ISSUE THREAD

**Issue by PicardOrion** [O-n-y/oxy.mods#91]
(sorry I could not add the Label "Mod")

0. OS: Windows 10 21H2

1. Game version: U42-514967-5

2. Create new issue with mod label

3. Write full description of issue and the way to reproduce it:
Subscribe to a few mods
Enable Mod Manager
Restart Steam in offline mode
Start ONI in offline mode
Mod Manager uninstalls ALL mods including itself (giving the corresponding message)

4. mod version: v3.2.23.271

5. Save Game: not needed, the issue occurs before save game is loaded

**Comment by O-n-y** [comment]
are you sure message from mod manager and not from the game itself?
screenshot the game with message

**Comment by O-n-y** [comment]
Also last version of the mod:  **2.13.6.104**

**Comment by O-n-y** [comment]
it is highly unlikely Mod Manager will uninstall mods, as it do not have such functionality built-in
(i.e. game mod manager doing this)

Mod Manager however will capture any such events and prints out those in the Log (if you install DebugConsole - you will see those), but still the action do not come from it.

**Comment by O-n-y** [comment]
this could only happen if the state of the mod pulled from the steam turned flag 'is_subscribed' **OFF**

**Comment by O-n-y** [comment]
i will check if we can avoid such behavior
