### ISSUE TITLE
[No Drop] - Mod is doing nothing

### ISSUE THREAD

**Issue by 767kaos** [O-n-y/oxy.mods#92]
ONI BUILD U42-514967-5 Spaced OUT! DLC is Enabled.
No Drop v1.2.4.27
Windows 10 Pro 64x 21H2 19044.1826

Mod Seems to do nothing, duplicants let go of items on stairs when catching breath, etc...
Triple checked mod is enabled and last version, also last in mod order and using Mod Updater
Downloaded game and mod on a fresh windows install... problem persists...
Started game with only [No Drop] mod enabled... problem persists...

[Bug Report.zip](https://github.com/O-n-y/oxy.mods/files/9195077/Bug.Report.zip)
.

**Comment by O-n-y** [comment]
DLC / Vanilla?

**Comment by 767kaos** [comment]
Spaced OUT! DLC is Enabled.

**Comment by O-n-y** [comment]
Finally got the chance to work on it, should be fixed on upcoming release buidl, will push for testing to BETA today
