### ISSUE TITLE
Mod Manager is obsessed with Ranching Overhaul

### ISSUE THREAD

**Issue by LoneMarauder** [O-n-y/oxy.mods#98]
At one time I had the mod "Ranching Overhaul" in my mod list, before it became outdated.  I unsubscribed to this mod, but now every time the game launches it tells me "Uninstalled: Ranching Overhaul".  I even had to reinstall completely due to a hard drive failure, and I'm assuming whatever config file is causing this issue was put back with my restore.

**Comment by O-n-y** [comment]
This is not related to the mod itself, as it operates with data provided by the game.
I can recommend to delete /mods folder, which should help to clear mods cache
